Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2021-08, with the labels that each got.

#197 refactor of candidate.ini, interco.txt and area.txt read
  data_test/tests_lpnamer/tests_integer/test_lpnamer_01/output/20210713-1635eco/reference_lp/problem-1-1-20210713-163528.mps
  data_test/tests_lpnamer/tests_integer/test_lpnamer_01/output/20210713-1635eco/reference_lp/structure.txt
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_1week/output/20210721-1451eco/lp/problem-1-1-20210721-145117.mps
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_1week/output/20210721-1451eco/lp/structure.txt
  data_test/tests_lpnamer/tests_relaxed/SmallTestSixCandidatesWithAlreadyInstalledCapacity-relaxed/output/20210720-1433eco/reference_lp/problem-1-1-20210720-143331.mps
  data_test/tests_lpnamer/tests_relaxed/SmallTestSixCandidatesWithAlreadyInstalledCapacity-relaxed/output/20210720-1433eco/reference_lp/problem-1-2-20210720-143331.mps
  data_test/tests_lpnamer/tests_relaxed/SmallTestSixCandidatesWithAlreadyInstalledCapacity-relaxed/output/20210720-1433eco/reference_lp/problem-1-3-20210720-143331.mps
  data_test/tests_lpnamer/tests_relaxed/SmallTestSixCandidatesWithAlreadyInstalledCapacity-relaxed/output/20210720-1433eco/reference_lp/problem-1-4-20210720-143331.mps
  data_test/tests_lpnamer/tests_relaxed/SmallTestSixCandidatesWithAlreadyInstalledCapacity-relaxed/output/20210720-1433eco/reference_lp/structure.txt
  src/cpp/exe/lpnamer/main.cpp
  src/cpp/helpers/StringUtils.cpp
  src/cpp/helpers/include/helpers/StringUtils.h
  src/cpp/helpers/solver_utils.cc
  src/cpp/helpers/solver_utils.h
  src/cpp/lpnamer/ActiveLinks.cpp
  src/cpp/lpnamer/ActiveLinks.h
  src/cpp/lpnamer/CMakeLists.txt
  src/cpp/lpnamer/Candidate.cpp
  src/cpp/lpnamer/Candidate.h
  src/cpp/lpnamer/CandidatesInitializer.cpp
  src/cpp/lpnamer/CandidatesInitializer.h
  src/cpp/lpnamer/Interco.cpp
  src/cpp/lpnamer/Interco.h
  src/cpp/lpnamer/IntercoDataMps.cpp
  src/cpp/lpnamer/IntercoDataMps.h
  src/cpp/lpnamer/IntercoINIReader.cpp
  src/cpp/lpnamer/IntercoINIReader.h
  src/cpp/lpnamer/StudyUpdater.cpp
  tests/cpp/CMakeLists.txt
  tests/cpp/lp_namer/ActiveLinkTest.cpp
  tests/cpp/lp_namer/CMakeLists.txt
  tests/cpp/lp_namer/IntercoINIReaderTest.cpp
  tests/cpp/lp_namer/StudyUpdateTest.cc
  tests/end_to_end/lpnamer/test_lpnamerEndToEnd.py
Labels: size/XXL

#198 Several investment on same link : add constraint for each candidate
  data_test/tests_lpnamer/tests_integer/test_one_link_one_candidate_1week/output/20210720-1024eco/lp/master.mps
  data_test/tests_lpnamer/tests_integer/test_one_link_one_candidate_1week/output/20210720-1024eco/lp/problem-1-1-20210720-102450.mps
  data_test/tests_lpnamer/tests_integer/test_one_link_one_candidate_1week/output/20210720-1024eco/lp/structure.txt
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_1week/output/20210721-1451eco/lp/master.mps
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_1week/output/20210721-1451eco/lp/problem-1-1-20210721-145117.mps
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_1week/output/20210721-1451eco/lp/structure.txt
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_1week_MR/output/20210721-1451eco/problem-1-1-20210721-145117.mps
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_1week_MR/output/20210721-1451eco/reference_lp/master.mps
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_1week_MR/output/20210721-1451eco/reference_lp/structure.txt
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_1week_MR/user/expansion/candidates.ini
  src/cpp/lpnamer/IntercoDataMps.cpp
  src/cpp/lpnamer/IntercoDataMps.h
  tests/end_to_end/lpnamer/test_lpnamerEndToEnd.py
Labels: size/XXL

#200 Feature/several invest refactor LinkProfile
  src/cpp/exe/lpnamer/main.cpp
  src/cpp/exe/study-updater/main.cpp
  src/cpp/lpnamer/CMakeLists.txt
  src/cpp/lpnamer/Candidate.cpp
  src/cpp/lpnamer/Candidate.h
  src/cpp/lpnamer/Candidates.cpp
  src/cpp/lpnamer/Candidates.h
  src/cpp/lpnamer/CandidatesINIReader.cpp
  src/cpp/lpnamer/CandidatesINIReader.h
  src/cpp/lpnamer/CandidatesInitializer.cpp
  src/cpp/lpnamer/CandidatesInitializer.h
  src/cpp/lpnamer/LinkProfile.cpp
  src/cpp/lpnamer/LinkProfile.h
  src/cpp/lpnamer/LinkProfileReader.cpp
  src/cpp/lpnamer/LinkProfileReader.h
  src/cpp/lpnamer/StudyUpdater.cpp
  src/cpp/lpnamer/StudyUpdater.h
  tests/cpp/lp_namer/CMakeLists.txt
  tests/cpp/lp_namer/CandidatesINIReaderTest.cpp
  tests/cpp/lp_namer/LinkProfileReaderTest.cpp
  tests/cpp/lp_namer/StudyUpdateTest.cc
Labels: size/XL

#201 Initialization of the interconnection object
  src/cpp/exe/lpnamer/main.cpp
  src/cpp/lpnamer/ActiveLinks.cpp
  src/cpp/lpnamer/ActiveLinks.h
  src/cpp/lpnamer/CMakeLists.txt
  src/cpp/lpnamer/Candidate.cpp
  src/cpp/lpnamer/Candidate.h
  src/cpp/lpnamer/Candidates.h
  src/cpp/lpnamer/CandidatesINIReader.cpp
  src/cpp/lpnamer/CandidatesINIReader.h
  src/cpp/lpnamer/CandidatesInitializer.cpp
  src/cpp/lpnamer/CandidatesInitializer.h
  src/cpp/lpnamer/Interco.cpp
  src/cpp/lpnamer/Interco.h
  src/cpp/lpnamer/LinkProfileReader.cpp
  src/cpp/lpnamer/LinkProfileReader.h
  tests/cpp/lp_namer/ActiveLinkTest.cpp
  tests/cpp/lp_namer/CandidatesINIReaderTest.cpp
  tests/cpp/lp_namer/LinkProfileReaderTest.cpp
Labels: size/XL

#210 mutualize download and extraction of precompiled libraries
  .github/workflows/centos7-system.yml
  .github/workflows/centos7-system_boost_1_75.yml
  .github/workflows/download-extract-precompiled-libraries-tgz/action.yml
  .github/workflows/download-extract-precompiled-libraries-zip/action.yml
  .github/workflows/releases-centos7.yml
  .github/workflows/releases-ubuntu.yml
  .github/workflows/releases-windows.yml
  .github/workflows/ubuntu-system.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/L, tech

#209 write master mps at each iteration
  CHANGELOG.md
  src/cpp/benders_sequential/Worker.cpp
Labels: enhancement, size/S

#213 correction of mps variable rename
  data_test/tests_lpnamer/tests_integer/test_lpnamer_01/output/economy/reference_lp/problem-1-1-20210713-163528.mps
  data_test/tests_lpnamer/tests_integer/test_one_link_one_candidate_1week/output/economy/reference_lp/problem-1-1-20210720-102450.mps
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_1week/output/economy/reference_lp/problem-1-1-20210721-145117.mps
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_simple_prob/output/economy/reference_lp/problem-1-1-20210721-145117.mps
  data_test/tests_lpnamer/tests_relaxed/SmallTestSixCandidatesWithAlreadyInstalledCapacity-relaxed/output/economy/reference_lp/problem-1-1-20210720-143331.mps
  data_test/tests_lpnamer/tests_relaxed/SmallTestSixCandidatesWithAlreadyInstalledCapacity-relaxed/output/economy/reference_lp/problem-1-2-20210720-143331.mps
  data_test/tests_lpnamer/tests_relaxed/SmallTestSixCandidatesWithAlreadyInstalledCapacity-relaxed/output/economy/reference_lp/problem-1-3-20210720-143331.mps
  data_test/tests_lpnamer/tests_relaxed/SmallTestSixCandidatesWithAlreadyInstalledCapacity-relaxed/output/economy/reference_lp/problem-1-4-20210720-143331.mps
  data_test/tests_lpnamer/tests_relaxed/test_one_link_one_candidate-relaxed/output/economy/reference_lp/problem-1-1-20210720-114739.mps
  data_test/tests_lpnamer/tests_relaxed/test_one_link_one_candidate-relaxed/output/economy/reference_lp/problem-1-2-20210720-114739.mps
  data_test/tests_lpnamer/tests_relaxed/test_one_link_one_candidate-relaxed/output/economy/reference_lp/problem-1-3-20210720-114739.mps
  data_test/tests_lpnamer/tests_relaxed/test_one_link_one_candidate-relaxed/output/economy/reference_lp/problem-1-4-20210720-114739.mps
  src/cpp/helpers/solver_utils.cc
Labels: size/M

#207 Feature/add problem modifier class
  data_test/tests_lpnamer/tests_integer/test_lpnamer_01/output/economy/reference_lp/master.mps
  data_test/tests_lpnamer/tests_integer/test_lpnamer_01/output/economy/reference_lp/problem-1-1-20210713-163528.mps
  data_test/tests_lpnamer/tests_integer/test_lpnamer_01/output/economy/reference_lp/structure.txt
  data_test/tests_lpnamer/tests_relaxed/SmallTestSixCandidatesWithAlreadyInstalledCapacity-relaxed/output/economy/reference_lp/master.mps
  data_test/tests_lpnamer/tests_relaxed/SmallTestSixCandidatesWithAlreadyInstalledCapacity-relaxed/output/economy/reference_lp/problem-1-1-20210720-143331.mps
  data_test/tests_lpnamer/tests_relaxed/SmallTestSixCandidatesWithAlreadyInstalledCapacity-relaxed/output/economy/reference_lp/problem-1-2-20210720-143331.mps
  data_test/tests_lpnamer/tests_relaxed/SmallTestSixCandidatesWithAlreadyInstalledCapacity-relaxed/output/economy/reference_lp/problem-1-3-20210720-143331.mps
  data_test/tests_lpnamer/tests_relaxed/SmallTestSixCandidatesWithAlreadyInstalledCapacity-relaxed/output/economy/reference_lp/problem-1-4-20210720-143331.mps
  data_test/tests_lpnamer/tests_relaxed/SmallTestSixCandidatesWithAlreadyInstalledCapacity-relaxed/output/economy/reference_lp/structure.txt
  src/cpp/exe/lpnamer/main.cpp
  src/cpp/helpers/solver_utils.cc
  src/cpp/helpers/solver_utils.h
  src/cpp/lpnamer/CMakeLists.txt
  src/cpp/lpnamer/Candidates.cpp
  src/cpp/lpnamer/Candidates.h
  src/cpp/lpnamer/ProblemModifier.cpp
  src/cpp/lpnamer/ProblemModifier.h
  tests/cpp/lp_namer/CMakeLists.txt
  tests/cpp/lp_namer/ProblemModifierTest.cpp
Labels: size/XXL

#208 remove not needed has-link-profile parameter in candidates.ini
  CHANGELOG.md
  README.md
  data_test/examples/xpansion-test-01-weights/user/expansion/candidates.ini
  data_test/examples/xpansion-test-01/user/expansion/candidates.ini
  data_test/examples/xpansion-test-02-new/user/expansion/candidates.ini
  data_test/examples/xpansion-test-02/user/expansion/candidates.ini
  data_test/examples/xpansion-test-03/user/expansion/candidates.ini
  data_test/examples/xpansion-test-04-mps-rounding/user/expansion/candidates.ini
  data_test/examples/xpansion-test-05-area-uppercase/user/expansion/candidates.ini
  data_test/examples/xpansion-test-05-area-uppercase/user/expansion/example - five candidates.ini
  data_test/test_case_7.1_structure/user/expansion/candidates.ini
  examples/SmallTestFiveCandidates/user/expansion/candidates.ini
  examples/SmallTestFiveCandidatesWithWeights/user/expansion/candidates.ini
  examples/SmallTestSixCandidatesWithAlreadyInstalledCapacity/user/expansion/candidates.ini
  examples/SmallTestSixCandidatesWithPlaylist/user/expansion/candidates.ini
  src/python/antares_xpansion/input_checker.py
  tests/end_to_end/examples/candidates_reader.py
  tests/end_to_end/examples/test/test_candidates_reader.py
Labels: size/M

#215 remove CandidateData in Candidate class and add enable parameters in candidate.ini read
  src/cpp/exe/lpnamer/main.cpp
  src/cpp/lpnamer/ActiveLinks.cpp
  src/cpp/lpnamer/CMakeLists.txt
  src/cpp/lpnamer/Candidate.cpp
  src/cpp/lpnamer/Candidate.h
  src/cpp/lpnamer/CandidatesINIReader.cpp
  src/cpp/lpnamer/CandidatesInitializer.cpp
  src/cpp/lpnamer/CandidatesInitializer.h
  tests/cpp/lp_namer/ActiveLinkTest.cpp
  tests/cpp/lp_namer/CandidatesINIReaderTest.cpp
  tests/cpp/lp_namer/LinkdataRecordTest.cc
  tests/cpp/lp_namer/StudyUpdateTest.cc
Labels: size/L

#217 add VariableFileReader class
  src/cpp/lpnamer/CMakeLists.txt
  src/cpp/lpnamer/Candidates.cpp
  src/cpp/lpnamer/ProblemModifier.h
  src/cpp/lpnamer/VariableFileReader.cpp
  src/cpp/lpnamer/VariableFileReader.h
  tests/cpp/lp_namer/CMakeLists.txt
  tests/cpp/lp_namer/VariableFileReaderTest.cpp
Labels: size/L
