Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2021-11, with the labels that each got.

#277 rename reportbendersmpi-0 into reportbendersmpi.txt since only master…
  src/cpp/exe/benders_mpi/main.cpp
Labels: size/XS

#278 repair windows-ci
  .github/workflows/windows-vcpkg.yml
Labels: size/XS

#279 Doc typo corrections
  README.md
  docs/build/0-INSTALL.md
  docs/build/2-Dependencies-install.md
  docs/build/3-Build.md
  docs/build/5-Installer-creation.md
  docs/developer-guide/0-Process.md
  docs/developer-guide/1-antares-solver.md
  mkdocs.yml
Labels: size/M

#282 add xpansion and antares versions as printable options
  CMakeLists.txt
  src/python/antares_xpansion/__version__.py.in
  src/python/antares_xpansion/input_parser.py
  src/python/launch.py
Labels: size/S

#288 Docs/relative gap
  README.md
  docs/CHANGELOG.md
  docs/build/1-Development-requirements.md
  docs/build/2-Dependencies-install.md
  docs/build/4-Tests.md
  docs/build/5-Installer-creation.md
  docs/developer-guide/0-Process.md
  docs/developer-guide/1-antares-solver.md
  docs/developer-guide/2-problem-modification.md
  docs/index.md
  docs/user-guide/0-introduction.md
  docs/user-guide/1-prepare-a-simulation.md
  docs/user-guide/2-Launching-an-Antares-Xpansion-optimization.md
Labels: size/L

#287 update docs
  docs/CHANGELOG.md
  docs/assets/media/ui.png
  docs/index.md
  docs/user-guide/1-prepare-a-simulation.md
  docs/user-guide/2-Launching-an-Antares-Xpansion-optimization.md
  src/python/antares_xpansion/input_parser.py
Labels: size/M

#289 Feature/lock study already launched
  requirements.txt
  src/python/antares_xpansion/study_locker.py
  src/python/launch.py
  tests/python/test_study_locker.py
Labels: size/L

#291 Introduce relative gap
  data_test/examples/xpansion-test-02-new/settings/generaldata.ini
  data_test/examples/xpansion-test-02/settings/generaldata.ini
  data_test/examples/xpansion-test-05-area-uppercase/settings/generaldata.ini
  data_test/test_case_7.1_structure/settings/generaldata.ini
  examples/SmallTestSixCandidatesWithAlreadyInstalledCapacity/settings/generaldata.ini
  examples/SmallTestSixCandidatesWithPlaylist/settings/generaldata.ini
  src/cpp/benders_sequential/BendersFunctions.cpp
  src/cpp/benders_sequential/BendersOptions.hxx
  src/cpp/benders_sequential/JsonWriter.cpp
  src/cpp/benders_sequential/JsonWriter.h
  src/cpp/benders_sequential/WorkerTrace.cpp
  src/cpp/benders_sequential/include/benders_sequential_core/ILogger.h
  src/cpp/benders_sequential/launcher.cpp
  src/cpp/exe/benders_mpi/main.cpp
  src/cpp/logger/IterationResultLog.cpp
  src/cpp/logger/User.cpp
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/input_checker.py
  src/python/antares_xpansion/xpansionConfig.py
  tests/cpp/logger/logger_test.cpp
  tests/end_to_end/examples/example_test.py
Labels: size/XL

#284 fix default install dir location
  CMakeLists.txt
  docs/build/4-Tests.md
  src/python/antares_xpansion/config_file_parser.py
  src/python/antares_xpansion/xpansionConfig.py
  src/python/config.yaml.in
  tests/CMakeLists.txt
  tests/end_to_end/examples/example_test.py
  tests/python/test_config_file_parser.py
Labels: size/L
