Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2021-05, with the labels that each got.

#117 Features/logger
  CMakeLists.txt
  INSTALL-centos.md
  INSTALL-ubuntu.md
  INSTALL-windows.md
  examples/xpansion-test-03/input/links/area1/area2.txt
  examples/xpansion-test-03/input/links/area1/invest_peak.txt
  examples/xpansion-test-03/input/links/area1/invest_semibase.txt
  src/cpp/CMakeLists.txt
  src/cpp/benders_mpi/BendersMPI.cpp
  src/cpp/benders_mpi/BendersMPI.h
  src/cpp/benders_sequential/Benders.cpp
  src/cpp/benders_sequential/BendersFunctions.cpp
  src/cpp/benders_sequential/BendersFunctions.h
  src/cpp/benders_sequential/CMakeLists.txt
  src/cpp/benders_sequential/common.cpp
  src/cpp/benders_sequential/common.h
  src/cpp/benders_sequential/include/benders_sequential_core/Benders.h
  src/cpp/benders_sequential/include/benders_sequential_core/ILogger.h
  src/cpp/benders_sequential/launcher.cpp
  src/cpp/benders_sequential/launcher.h
  src/cpp/exe/analyse/analyse_mps.cpp
  src/cpp/exe/benders_mpi/CMakeLists.txt
  src/cpp/exe/benders_mpi/main.cpp
  src/cpp/exe/benders_sequential/CMakeLists.txt
  src/cpp/exe/benders_sequential/main.cpp
  src/cpp/exe/merge/CMakeLists.txt
  src/cpp/exe/merge/merge_mps.cpp
  src/cpp/logger/CMakeLists.txt
  src/cpp/logger/CandidateLog.cpp
  src/cpp/logger/CandidateLog.h
  src/cpp/logger/Commons.h
  src/cpp/logger/IterationResultLog.cpp
  src/cpp/logger/IterationResultLog.h
  src/cpp/logger/Master.cpp
  src/cpp/logger/User.cpp
  src/cpp/logger/include/logger/Master.h
  src/cpp/logger/include/logger/User.h
  tests/cpp/CMakeLists.txt
  tests/cpp/logger/CMakeLists.txt
  tests/cpp/logger/logger_test.cpp
Labels: enhancement, size/XL

#126 WIP : Clean unused result after each simulation steps
  requirements-tests.txt
  src/python/antares_xpansion/driver.py
  src/python/antares_xpansion/study_output_cleaner.py
  src/python/antares_xpansion/xpansionConfig.py
  tests/python/test_study_output_cleaner.py
Labels: enhancement

#130 Fix for use of study on mount drive
  src/python/antares_xpansion/xpansionConfig.py
Labels: bug, size/XS

#135 feature: add -i as alternative to --dataDir and -m for --method
  src/python/antares_xpansion/xpansionConfig.py
Labels: enhancement, size/XS

#136 Features/installer single binary
  .github/workflows/centos7-system.yml
  .github/workflows/centos7-system_boost_1_75.yml
  .github/workflows/linux-system.yml
  .github/workflows/releases-centos7.yml
  .github/workflows/releases-linux.yml
  .github/workflows/releases-windows.yml
  .github/workflows/single-file-creation-tgz/action.yml
  .github/workflows/single-file-creation-zip/action.yml
  .github/workflows/windows-vcpkg.yml
  antares-version.json
Labels: size/L

#141 display duration of antares and lp_namer steps
  src/python/antares_xpansion/driver.py
Labels: enhancement, size/S

#144 Update LICENCE
  LICENSE
Labels: size/XS

#150 fix: useless check causes malfunction
  src/cpp/lpnamer/IntercoDataMps.cpp
Labels: size/XS

#149 Fix/simulation name issue when running steps individually
  src/python/antares_xpansion/driver.py
  src/python/antares_xpansion/xpansionConfig.py
Labels: size/XL

#154 Multisolver correction for or-tools dependency remove
  CMakeLists.txt
  src/cpp/benders_mpi/BendersMPI.cpp
  src/cpp/benders_mpi/CMakeLists.txt
  src/cpp/benders_sequential/BendersFunctions.cpp
  src/cpp/benders_sequential/CMakeLists.txt
  src/cpp/benders_sequential/Worker.cpp
  src/cpp/benders_sequential/Worker.h
  src/cpp/benders_sequential/WorkerMaster.cpp
  src/cpp/benders_sequential/launcher.cpp
  src/cpp/exe/analyse/CMakeLists.txt
  src/cpp/exe/benders_mpi/main.cpp
  src/cpp/exe/merge/merge_mps.cpp
  src/cpp/helpers/CMakeLists.txt
  src/cpp/helpers/ortools_utils.cc
  src/cpp/helpers/ortools_utils.h
  src/cpp/lpnamer/CMakeLists.txt
  src/cpp/multisolver_interface/CMakeLists.txt
  src/cpp/multisolver_interface/SolverAbstract.h
  src/cpp/multisolver_interface/SolverCbc.cpp
  src/cpp/multisolver_interface/SolverCbc.h
  src/cpp/multisolver_interface/SolverClp.cpp
  src/cpp/multisolver_interface/SolverClp.h
  src/cpp/multisolver_interface/SolverCplex.cpp
  src/cpp/multisolver_interface/SolverCplex.h
  src/cpp/multisolver_interface/SolverXpress.cpp
  src/cpp/multisolver_interface/SolverXpress.h
  tests/cpp/CMakeLists.txt
  tests/cpp/helpers/ORToolsTest.cc
Labels: size/XL

#155 add unit_solver test to ctest and linux support for unit_solver test
  tests/cpp/solvers_interface/CMakeLists.txt
  tests/cpp/solvers_interface/define_datas.cpp
Labels: size/M

#153 check gap defined by user instead of hard coded 1e-3 for problem_status
  src/cpp/benders_sequential/JsonWriter.cpp
  src/cpp/benders_sequential/JsonWriter.h
  src/cpp/benders_sequential/launcher.cpp
  src/cpp/exe/benders_mpi/main.cpp
Labels: bug, size/S

#157 Feature/xpress 8 11 use
  src/cpp/helpers/ortools_utils.cc
  src/cpp/multisolver_interface/SolverXpress.cpp
Labels: size/S
