Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2021-09, with the labels that each got.

#221 invalid constraint creation on binary constraint
  src/cpp/lpnamer/LauncherHelpers.cpp
Labels: bug, size/XS

#223 Feature/update version 0.5.0 rc2
  .gitlab-ci.yml
  CHANGELOG.md
  CMakeLists.txt
  antares-version.json
Labels: enhancement, size/M

#226 Fix/direct indirect hurdles cost
  data_test/tests_lpnamer/tests_integer/test_lpnamer_01/output/economy/reference_lp/problem-1-1-20210713-163528.mps
  src/cpp/benders_sequential/Worker.cpp
  src/cpp/lpnamer/LinkProblemsGenerator.cpp
  src/cpp/lpnamer/ProblemModifier.cpp
  src/cpp/lpnamer/ProblemModifier.h
  src/cpp/lpnamer/VariableFileReader.cpp
  src/cpp/lpnamer/VariableFileReader.h
  tests/cpp/lp_namer/ProblemModifierTest.cpp
  tests/cpp/lp_namer/VariableFileReaderTest.cpp
  tests/end_to_end/examples/example_test.py
Labels: size/XXL

#232 first test of sonarcloud integration
  .github/workflows/sonarcloud.yml
  sonar-project.properties
Labels: size/L, tech

#233 add code_coverage
  .github/workflows/sonarcloud.yml
  CMakeLists.txt
  cmake/CodeCoverage.cmake
  cmake/SetUpCoverage.cmake
  sonar-project.properties
Labels: size/L, tech

#235 Doc/new doc
  docs/assets/Icone.png
  docs/assets/antares.png
  docs/assets/logo.png
  docs/assets/media/image1.png
  docs/assets/media/image10.png
  docs/assets/media/image11.png
  docs/assets/media/image12.png
  docs/assets/media/image13.png
  docs/assets/media/image14.png
  docs/assets/media/image15.png
  docs/assets/media/image16.png
  docs/assets/media/image17.png
  docs/assets/media/image18.png
  docs/assets/media/image19.png
  docs/assets/media/image2.png
  docs/assets/media/image20.png
  docs/assets/media/image21.png
  docs/assets/media/image22.png
  docs/assets/media/image23.png
  docs/assets/media/image3.png
  docs/assets/media/image4.png
  docs/assets/media/image5.png
  docs/assets/media/image6.png
  docs/assets/media/image7.png
  docs/assets/media/image8.png
  docs/assets/media/image9.png
  docs/index.md
  docs/stylesheets/extra.css
  docs/user guide/1-prepare-a-simulation.md
  docs/user guide/2-Launching-an-Antares-Xpansion-optimization.md
  mkdocs.yml
  readthedocs.yml
  requirements-doc.txt
Labels: documentation, size/XXL

#236 test with pytest-cov and sonarcloud
  .github/workflows/sonarcloud.yml
  requirements-tests.txt
  sonar-project.properties
  tests/CMakeLists.txt
Labels: size/S, tech

#237 CI with docker
  .github/workflows/centos7-system.yml
  .github/workflows/releases-centos7.yml
  docker/build-docker-file-src.sh
  docker/centos7
  docker/centos7-src
Labels: size/L, tech

#240 Feature/xpress centos
  CMakeLists.txt
  cmake/FindXPRESS.cmake
  cmake/FindXpress.cmake
  src/cpp/multisolver_interface/CMakeLists.txt
  src/cpp/multisolver_interface/SolverXpress.cpp
Labels: size/L, tech
