Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2021-12, with the labels that each got.

#292 Feature/refactor xpansion driver
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/driver.py
  src/python/launch.py
Labels: size/L

#297 fix gui bug on ub20 && update doc
  docs/build/6-ui-creation.md
  src/python/antares-xpansion-ui.py
Labels: size/M

#302 Fix/broken medium tests
  docs/build/4-Tests.md
  tests/CMakeLists.txt
  tests/end_to_end/examples/example_test.py
  tests/end_to_end/examples/pytest.ini
Labels: size/XL

#309 copy study for tests
  tests/end_to_end/examples/example_test.py
Labels: size/M

#307 feature: accept Coin as accepted solver name
  src/CMakeLists.txt
  src/python/antares_xpansion/xpansion_study_reader.py
  tests/python/test_xpansion_study_reader.py
Labels: size/XS

#306 fix: change way to check available cores
  src/python/antares-xpansion-ui.py
Labels: size/S

#308 print finish message
  src/python/launch.py
Labels: size/S

#304 Fix/run all tests
  .github/workflows/windows-vcpkg.yml
  CMakeLists.txt
  requirements-tests.txt
  tests/CMakeLists.txt
  tests/end_to_end/examples/example_test.py
  tests/python/file_creation.py
  tests/python/test_antares_driver.py
  tests/python/test_problem_generator_driver.py
Labels: size/L

#310 Feature/print antares version in json output file
  src/cpp/benders_sequential/JsonWriter.cpp
  src/cpp/config.h.in
Labels: size/XS

#311 remove xpress uncontrolled stdout
  src/cpp/multisolver_interface/SolverXpress.cpp
Labels: size/S

#317 fix: improve a bit the additional constraints' reader logs
  src/cpp/lpnamer/input_reader/AdditionalConstraintsReader.cpp
Labels: size/S

#316 Fix/force oversuscribe for linux
  src/python/antares_xpansion/benders_driver.py
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/driver.py
  src/python/antares_xpansion/input_parser.py
  src/python/antares_xpansion/xpansionConfig.py
  tests/end_to_end/examples/example_test.py
  tests/python/test_benders_driver.py
  tests/python/test_input_parser.py
Labels: size/L

#326 Corrections to problem formulation
  docs/user-guide/optimization-principles/problem-formalization.md
Labels: size/L

#329 Doc/update readme
  INSTALL.md
  README.md
  docs/CHANGELOG.md
  docs/user-guide/get-started/launching-optimization.md
  documentation/CMakeLists.txt
  documentation/Doxyfile.in
Labels: size/XXL

#318 move out.json in the new dir /expansion
  data_test/mini_instance_INFEAS/options_default.txt
  data_test/mini_instance_LP/options_default.txt
  data_test/mini_instance_MIP/options_default.txt
  data_test/mini_instance_UNBOUNDED/options_default.txt
  data_test/mini_network/options_default.txt
  data_test/mini_network/options_weights.txt
  src/cpp/benders/benders_core/BendersOptions.hxx
  src/cpp/benders/benders_core/launcher.cpp
  src/cpp/benders/benders_mpi/include/launch_mpi.h
  src/cpp/benders/benders_mpi/launch_mpi.cpp
  src/cpp/benders/benders_sequential/SequentialLaunch.cpp
  src/cpp/exe/benders_mpi/main.cpp
  src/cpp/exe/benders_sequential/main.cpp
  src/cpp/exe/merge/merge_mps.cpp
  src/cpp/exe/study-updater/main.cpp
  src/python/antares_xpansion/benders_driver.py
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/driver.py
  src/python/antares_xpansion/study_updater_driver.py
  src/python/antares_xpansion/xpansionConfig.py
  tests/end_to_end/benders/test_bendersEndToEnd.py
  tests/end_to_end/benders/test_bendersmpibendersEndToEnd.py
  tests/end_to_end/examples/example_test.py
  tests/python/test_study_updater.py
Labels: size/L

#321 Feature/remove rand aggregation
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/BendersOptions.hxx
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/common.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_mpi/include/BendersMPI.h
  src/cpp/benders/benders_sequential/Benders.cpp
  src/python/antares_xpansion/xpansionConfig.py
Labels: size/L

#324 any whitespace is a separator
  src/python/antares_xpansion/input_checker.py
Labels: size/XS

#322 use Path class
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/BendersOptions.cpp
  src/cpp/benders/benders_core/Worker.cpp
  src/cpp/benders/benders_core/include/common.h
  src/cpp/benders/benders_mpi/launch_mpi.cpp
  src/cpp/benders/benders_sequential/SequentialLaunch.cpp
  src/cpp/exe/analyse/analyse_mps.cpp
  src/cpp/exe/benders_mpi/main.cpp
  src/cpp/exe/benders_sequential/main.cpp
  src/cpp/exe/lpnamer/main.cpp
  src/cpp/exe/merge/merge_mps.cpp
  src/cpp/exe/study-updater/main.cpp
  src/cpp/helpers/include/helpers/Path.h
  src/cpp/lpnamer/helper/common_lpnamer.h
  src/cpp/lpnamer/input_reader/LinkProfileReader.cpp
  src/cpp/lpnamer/problem_modifier/LauncherHelpers.cpp
  src/cpp/lpnamer/problem_modifier/LauncherHelpers.h
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.cpp
  src/cpp/lpnamer/problem_modifier/StudyUpdater.cpp
  tests/cpp/lp_namer/StudyUpdateTest.cc
Labels: size/XL

#333 Update sonar cloud properties
  sonar-project.properties
Labels: size/XS

#331 Add details on how to run an example after installation instructions
  README.md
  docs/user-guide/get-started/installation.md
Labels: size/S

#325 allow log_level as option in settings.ini
  docs/user-guide/get-started/settings-definition.md
  src/cpp/benders/benders_core/BendersOptions.hxx
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/input_checker.py
  src/python/antares_xpansion/xpansionConfig.py
Labels: size/M
