Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2021-04, with the labels that each got.

#105 Fix mps coin
  src/src_cpp/src_helpers/ortools_utils.cc
  src/src_cpp/src_helpers/ortools_utils.h
Labels: bug, size/L

#96 add antares-study-updater in installer
  CMakeLists.txt
Labels: PR: waiting for review, enhancement, size/S

#108 Features/add changelog
  CHANGELOG.md
Labels: documentation, size/M

#103 Fix/archive dll windows
  CMakeLists.txt
  INSTALL-centos.md
  INSTALL-ubuntu.md
  INSTALL-windows.md
Labels: bug, size/S

#104 multiple xpansion launch
  src/src_python/antares_xpansion/driver.py
Labels: PR: waiting for review, bug, size/M

#110 Features/integrate benders test to ctest
  .github/workflows/centos7-system.yml
  .github/workflows/linux-system.yml
  .github/workflows/releases-centos7.yml
  .github/workflows/releases-linux.yml
  .github/workflows/releases-windows.yml
  .github/workflows/windows-vcpkg.yml
  INSTALL-centos.md
  INSTALL-ubuntu.md
  INSTALL-windows.md
  src/tests/CMakeLists.txt
  src/tests/bendersEndToEnd/test_bendersEndToEnd.py
Labels: enhancement, size/L

#113 update documentation for 0.2.0
  CMakeLists.txt
  documentation/antares-xpansion-user-guide-0.1.0.docx
  documentation/antares-xpansion-user-guide-0.1.0.pdf
  documentation/antares-xpansion-user-guide-0.2.0.docx
  documentation/antares-xpansion-user-guide-0.2.0.pdf
Labels: documentation

#122 Feature/benders for logging
  INSTALL-centos.md
  INSTALL-ubuntu.md
  INSTALL-windows.md
  examples/xpansion-test-03/input/links/area1/area2.txt
  examples/xpansion-test-03/input/links/area1/invest_peak.txt
  examples/xpansion-test-03/input/links/area1/invest_semibase.txt
  src/cpp/benders_mpi/BendersMPI.cpp
  src/cpp/benders_mpi/BendersMPI.h
  src/cpp/benders_sequential/Benders.cpp
  src/cpp/benders_sequential/BendersFunctions.cpp
  src/cpp/benders_sequential/BendersFunctions.h
  src/cpp/benders_sequential/common.cpp
  src/cpp/benders_sequential/include/benders_sequential_core/Benders.h
  src/cpp/benders_sequential/include/benders_sequential_core/ILogger.h
  src/cpp/benders_sequential/launcher.cpp
  src/cpp/benders_sequential/launcher.h
  src/cpp/exe/analyse/analyse_mps.cpp
  src/cpp/exe/benders_mpi/CMakeLists.txt
  src/cpp/exe/benders_mpi/main.cpp
  src/cpp/exe/benders_sequential/CMakeLists.txt
  src/cpp/exe/benders_sequential/main.cpp
  src/cpp/exe/merge/CMakeLists.txt
  src/cpp/exe/merge/merge_mps.cpp
  src/cpp/logger/CandidateLog.cpp
  src/cpp/logger/CandidateLog.h
  src/cpp/logger/Master.cpp
  src/cpp/logger/User.cpp
  src/cpp/logger/include/logger/Master.h
  src/cpp/logger/include/logger/User.h
  tests/cpp/CMakeLists.txt
  tests/cpp/benders_sequential/CMakeLists.txt
  tests/cpp/benders_sequential/benders_core_test.cpp
  tests/cpp/logger/logger_test.cpp
Labels: PR: waiting for review, enhancement
