Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2021-03, with the labels that each got.

#50 Fix : parse ini file with duplicate sections
  src/src_python/antares_xpansion/driver.py
Labels: bug

#43 Features/method option review
  .github/workflows/centos7-system.yml
  .github/workflows/linux-system.yml
  .github/workflows/releases-centos7.yml
  .github/workflows/releases-linux.yml
  .github/workflows/releases-windows.yml
  CMakeLists.txt
  INSTALL-centos.md
  INSTALL-ubuntu.md
  INSTALL-windows.md
  INSTALL.md
  README.md
  src/src_python/antares_xpansion/xpansionConfig.py
Labels: enhancement

#49 Use of precompiled antares-solver
  .github/workflows/centos7-system.yml
  .github/workflows/linux-system.yml
  .github/workflows/releases-centos7.yml
  .github/workflows/releases-linux.yml
  .github/workflows/releases-windows.yml
  .github/workflows/windows-vcpkg.yml
  CMakeLists.txt
  antares-version.json
  cmake/dependencies/CMakeLists.txt
  cmake/dependencies/CMakeLists.txt.in
  cmake/json-cmake-1.1.0/JSONParser.cmake
  cmake/json-cmake-1.1.0/LICENSE
  cmake/json-cmake-1.1.0/README.md
  src/CMakeLists.txt
Labels: enhancement

#55 remove -c option
  src/src_python/antares_xpansion/xpansionConfig.py
Labels: enhancement

#57 Fix/allow empty settings lines
  src/src_python/antares_xpansion/driver.py
  src/src_python/antares_xpansion/input_checker.py
Labels: PR: waiting for review, bug

#51 add test resources
  .gitignore
  data_test/mini_network/SP1.mps
  data_test/mini_network/SP2.mps
  data_test/mini_network/benders_output_trace.csv
  data_test/mini_network/master.mps
  data_test/mini_network/options_default.txt
  data_test/mini_network/structure.txt
  data_test/mps/lp1.mps
  data_test/mps/mip_toy_prob.mps
Labels: enhancement

#53 Fix/config yaml no mpi
  src/CMakeLists.txt
  src/src_python/config.yaml.in
Labels: bug

#56 update INSTALL.md to indicate tests and all cmake configure options
  INSTALL-centos.md
  INSTALL-ubuntu.md
  INSTALL-windows.md
  INSTALL.md
Labels: documentation

#60 Don't use ConfigParser for generaldata.ini change but parse all file
  CMakeLists.txt
  src/src_python/antares_xpansion/driver.py
Labels: bug

#64 Correction bug JSON operational_cost
  .gitignore
  data_test/mini_network/SP1.mps
  data_test/mini_network/SP2.mps
  data_test/mini_network/benders_output_trace.csv
  data_test/mini_network/master.mps
  data_test/mini_network/options_default.txt
  data_test/mini_network/structure.txt
  data_test/mps/lp1.mps
  data_test/mps/mip_toy_prob.mps
  src/src_cpp/src_mpi/BendersMPI.cpp
  src/src_cpp/src_sequential/Benders.cpp
Labels: bug

#72 Fix/python set GitHub actions
  .github/workflows/linux-system.yml
  .github/workflows/releases-linux.yml
  .github/workflows/releases-windows.yml
  .github/workflows/windows-vcpkg.yml
Labels: bug

#69 remove include-trace parameters in optimization section
  src/src_python/antares_xpansion/driver.py
Labels: PR: waiting for review, bug

#65 Fix/incorrect nb years if playlist
  .github/workflows/centos7-system.yml
  .github/workflows/linux-system.yml
  .github/workflows/releases-centos7.yml
  .github/workflows/releases-linux.yml
  .github/workflows/releases-windows.yml
  .github/workflows/windows-vcpkg.yml
  INSTALL-centos.md
  INSTALL-ubuntu.md
  INSTALL-windows.md
  src/src_cpp/src_test/CMakeLists.txt
  src/src_python/antares_xpansion/driver.py
  src/src_python/antares_xpansion/general_data_reader.py
  src/src_python/antares_xpansion/test/test_ini_reader.py
  src/tests/CMakeLists.txt
Labels: bug

#77 add release/* branches to CI
  .github/workflows/centos7-system.yml
  .github/workflows/linux-system.yml
  .github/workflows/windows-vcpkg.yml
Labels: bug

#75 add rc indication in installer
  CMakeLists.txt
Labels: PR: waiting for review, bug

#74 fix use of space in install dir
  src/src_python/antares_xpansion/driver.py
Labels: bug

#80 update documentation (remove unavailable option)
  .github/workflows/releases-windows.yml
  documentation/antares-xpansion-user-guide-0.1.0.docx
  documentation/antares-xpansion-user-guide-0.1.0.pdf
Labels: documentation

#81 remove output after tests
  src/tests/examples/example_test.py
Labels: bug

#82 Fix/update run vcpkg gh action
  .github/workflows/centos7-system.yml
  .github/workflows/linux-system.yml
  .github/workflows/releases-centos7.yml
  .github/workflows/releases-linux.yml
  .github/workflows/releases-windows.yml
  .github/workflows/windows-vcpkg.yml
Labels: bug, enhancement

#84 Features/log review
  src/src_cpp/exe/exe_lpnamer/main.cpp
  src/src_cpp/exe/exe_mpi/main.cpp
  src/src_cpp/exe/exe_sequential/main.cpp
  src/src_cpp/exe/merge/merge_mps.cpp
  src/src_cpp/src_lpnamer/IntercoDataMps.cpp
  src/src_cpp/src_mpi/BendersMPI.cpp
  src/src_cpp/src_mpi/BendersMPI.h
  src/src_cpp/src_sequential/Benders.cpp
  src/src_cpp/src_sequential/Benders.h
  src/src_cpp/src_sequential/BendersFunctions.cpp
  src/src_cpp/src_sequential/BendersFunctions.h
  src/src_cpp/src_sequential/BendersOptions.cpp
  src/src_cpp/src_sequential/Worker.cpp
  src/src_cpp/src_sequential/Worker.h
  src/src_cpp/src_sequential/WorkerMaster.cpp
  src/src_cpp/src_sequential/WorkerSlave.cpp
  src/src_cpp/src_sequential/launcher.cpp
  src/src_cpp/src_test/ORToolsTest.cc
  src/src_python/antares_xpansion/driver.py
  src/src_python/antares_xpansion/xpansion_utils.py
  src/tests/CMakeLists.txt
  src/tests/examples/example_test.py
Labels: enhancement

#86 Features/update version
  CMakeLists.txt
  src/src_cpp/exe/exe_mpi/main.cpp
  src/src_cpp/exe/exe_sequential/main.cpp
  src/src_cpp/exe/merge/merge_mps.cpp
  src/src_cpp/src_sequential/launcher.cpp
Labels: enhancement

#40 Update input of antares study
  .github/workflows/centos7-system.yml
  .github/workflows/linux-system.yml
  .github/workflows/releases-centos7.yml
  .github/workflows/releases-linux.yml
  .github/workflows/releases-windows.yml
  .github/workflows/windows-vcpkg.yml
  CMakeLists.txt
  INSTALL-ubuntu.md
  INSTALL.md
  README.md
  cmake/SetUpCoverage.cmake
  conception/out_merge.json
  conception/out_seq.json
  conception/output_example.schema.json
  data_test/mini_instance_MIP/options_default.txt
  src/src_cpp/exe/CMakeLists.txt
  src/src_cpp/exe/exe_lpnamer/CMakeLists.txt
  src/src_cpp/exe/exe_lpnamer/main.cpp
  src/src_cpp/exe/exe_mpi/main.cpp
  src/src_cpp/exe/exe_study-updater/CMakeLists.txt
  src/src_cpp/exe/exe_study-updater/main.cpp
  src/src_cpp/exe/merge/merge_mps.cpp
  src/src_cpp/src_helpers/CMakeLists.txt
  src/src_cpp/src_helpers/JsonXpansionReader.cpp
  src/src_cpp/src_helpers/JsonXpansionReader.h
  src/src_cpp/src_helpers/ortools_utils.cc
  src/src_cpp/src_lpnamer/AdditionalConstraints.cpp
  src/src_cpp/src_lpnamer/AdditionalConstraints.h
  src/src_cpp/src_lpnamer/AdditionalConstraintsReader.cpp
  src/src_cpp/src_lpnamer/AdditionalConstraintsReader.h
  src/src_cpp/src_lpnamer/CMakeLists.txt
  src/src_cpp/src_lpnamer/CandidatesInitializer.cpp
  src/src_cpp/src_lpnamer/CandidatesInitializer.h
  src/src_cpp/src_lpnamer/IntercoDataMps.cpp
  src/src_cpp/src_lpnamer/IntercoDataMps.h
  src/src_cpp/src_lpnamer/LauncherHelpers.cpp
  src/src_cpp/src_lpnamer/LauncherHelpers.h
  src/src_cpp/src_lpnamer/LinkdataRecord.cpp
  src/src_cpp/src_lpnamer/StudyUpdater.cpp
  src/src_cpp/src_lpnamer/StudyUpdater.h
  src/src_cpp/src_lpnamer/common_lpnamer.h
  src/src_cpp/src_mpi/common_mpi.h
  src/src_cpp/src_sequential/Benders.h
  src/src_cpp/src_sequential/BendersOptions.cpp
  src/src_cpp/src_sequential/BendersOptions.hxx
  src/src_cpp/src_sequential/JsonWriter.cpp
  src/src_cpp/src_sequential/JsonWriter.h
  src/src_cpp/src_sequential/Worker.cpp
  src/src_cpp/src_sequential/launcher.cpp
  src/src_cpp/src_sequential/launcher.h
  src/src_cpp/src_test/AdditionalConstraintsReaderTest.cc
  src/src_cpp/src_test/CMakeLists.txt
  src/src_cpp/src_test/JsonXpansionReaderTest.cc
  src/src_cpp/src_test/LinkdataRecordTest.cc
  src/src_cpp/src_test/SimpleTest.cc
  src/src_cpp/src_test/StudyUpdateTest.cc
  src/src_python/antares_xpansion/driver.py
  src/src_python/antares_xpansion/xpansionConfig.py
  src/src_python/config.yaml.in
Labels: enhancement, size/XXL
