Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2022-08, with the labels that each got.

#483 Minor code corrections
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/common.h
  src/cpp/benders/benders_sequential/BendersSequential.cpp
  src/cpp/benders/benders_sequential/include/BendersSequential.h
Labels: size/M

#490 Feature/adr
  conception/Architecture_decision_records/Template.md
  conception/Architecture_decision_records/Use_ADR.md
Labels: size/M

#495 Rollback unwanted change on candidate option management
  src/python/antares_xpansion/input_checker.py
Labels: size/S

#496 Fix write coin basis
  src/cpp/multisolver_interface/SolverCbc.cpp
Labels: bug, size/S

#494 Fix/488 fix algorithm not stopping at max iteration
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/CMakeLists.txt
  src/cpp/benders/benders_core/StartUp.cpp
  src/cpp/benders/benders_core/include/StartUp.h
  src/cpp/exe/benders_mpi/main.cpp
  src/cpp/exe/benders_sequential/main.cpp
  tests/cpp/TestDoubles/LoggerStub.h
  tests/cpp/TestDoubles/WriterStub.h
  tests/cpp/restart_benders/CMakeLists.txt
  tests/cpp/restart_benders/restart_lib_tests.cpp
Labels: size/L

#498 Fix post merge
  tests/cpp/TestDoubles/LoggerStub.h
Labels: size/XS

#497 Bump sonar project version
  sonar-project.properties
Labels: size/XS

#501 Fine tune sonar
  .github/workflows/sonarcloud.yml
  sonar-project.properties
Labels: size/S

#500 ADR MPI or multithreading
  conception/Architecture_decision_records/MPI_or_multithreading.md
Labels: size/S

#505 Fix typo
  docs/CHANGELOG.md
Labels: documentation, size/S
