Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2022-03, with the labels that each got.

#387 fix crash when weight file and non-contiguos-playlist are used at the same time
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/driver.py
  src/python/antares_xpansion/general_data_reader.py
  src/python/antares_xpansion/problem_generator_driver.py
  src/python/antares_xpansion/yearly_weight_writer.py
  tests/python/test_ini_reader.py
  tests/python/test_problem_generator_driver.py
  tests/python/test_yearly_weigth_writer.py
Labels: size/L

#385 delete obsolete options in examples/ and data_test/
  data_test/examples/additionnal-constraints-binary/user/expansion/candidates.ini
  data_test/examples/additionnal-constraints/user/expansion/candidates.ini
  data_test/examples/empty-link-profile/user/expansion/candidates.ini
  data_test/examples/hurdles-cost-profile-value-over-one/user/expansion/candidates.ini
  data_test/examples/link-profile-with-empty-week/user/expansion/candidates.ini
  data_test/examples/xpansion-test-01-hurdles-cost/user/expansion/candidates.ini
  data_test/examples/xpansion-test-01-weights/user/expansion/candidates.ini
  data_test/examples/xpansion-test-01/user/expansion/candidates.ini
  data_test/examples/xpansion-test-02-new/user/expansion/candidates.ini
  data_test/examples/xpansion-test-02/user/expansion/candidates.ini
  data_test/examples/xpansion-test-03/user/expansion/candidates.ini
  data_test/examples/xpansion-test-04-mps-rounding/user/expansion/candidates.ini
  data_test/examples/xpansion-test-05-area-uppercase/user/expansion/candidates.ini
  data_test/examples/xpansion-test-05-area-uppercase/user/expansion/example - five candidates.ini
  data_test/test_case_7.1_structure/user/expansion/candidates.ini
  data_test/test_case_7.1_structure/user/expansion/other_inputs_for_test/candidates-identicalnames.ini
  data_test/test_case_7.1_structure/user/expansion/other_inputs_for_test/candidates-unknownarg.ini
  data_test/test_case_7.1_structure/user/expansion/other_inputs_for_test/candidates-unknownlink.ini
  data_test/tests_lpnamer/tests_integer/test_lpnamer_01/user/expansion/candidates.ini
  data_test/tests_lpnamer/tests_relaxed/SmallTestSixCandidatesWithAlreadyInstalledCapacity-relaxed/user/expansion/candidates.ini
  examples/SmallTestFiveCandidates/user/expansion/candidates.ini
  examples/SmallTestFiveCandidatesWithWeights/user/expansion/candidates.ini
  examples/SmallTestSixCandidatesWithAlreadyInstalledCapacity/user/expansion/candidates.ini
  examples/SmallTestSixCandidatesWithPlaylist/user/expansion/candidates.ini
  examples/additionnal-constraints-binary/user/expansion/candidates.ini
  examples/additionnal-constraints/user/expansion/candidates.ini
Labels: size/L

#389 Update changelog
  docs/CHANGELOG.md
Labels: size/XS

#390 put duplicate var in constant
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/SimulationOptions.cpp
  src/cpp/benders/benders_core/Worker.cpp
  src/cpp/benders/benders_core/include/SimulationOptions.hxx
  src/cpp/benders/benders_core/include/Worker.h
  src/cpp/benders/benders_core/include/common.h
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/xpansionConfig.py
Labels: size/S

#383 unify actions release and standard CI
  .github/workflows/build-userguide.yml
  .github/workflows/centos7-system-deps-build.yml
  .github/workflows/centos7-system.yml
  .github/workflows/release-userguide.yml
  .github/workflows/releases-centos7.yml
  .github/workflows/releases-ubuntu.yml
  .github/workflows/releases-windows.yml
  .github/workflows/ubuntu-system-deps-build.yml
  .github/workflows/ubuntu-system.yml
  .github/workflows/vcpkg.yml
  .github/workflows/windows-vcpkg-deps-build.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/XXL, tech

#384 remove python writing solver log
  src/python/antares_xpansion/benders_driver.py
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/driver.py
  src/python/antares_xpansion/xpansionConfig.py
  tests/python/test_benders_driver.py
Labels: size/L

#393 move logger headers to include_dir
  src/cpp/benders/logger/CMakeLists.txt
  src/cpp/benders/logger/include/CandidateLog.h
  src/cpp/benders/logger/include/Commons.h
  src/cpp/benders/logger/include/IterationResultLog.h
Labels: size/XS

#394 fix Xpress fail
  src/cpp/multisolver_interface/SolverXpress.cpp
Labels: size/XS

#388 adapt BendersBase methods visibility
  docs/developer-guide/install_from_sources/4-Tests.md
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/Worker.cpp
  src/cpp/benders/benders_core/WorkerMaster.cpp
  src/cpp/benders/benders_core/WorkerSlave.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/Worker.h
  src/cpp/benders/benders_core/include/WorkerMaster.h
  src/cpp/benders/benders_core/include/WorkerSlave.h
  src/cpp/benders/benders_core/include/common.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_mpi/include/BendersMPI.h
  src/cpp/benders/benders_sequential/BendersSequential.cpp
  src/cpp/benders/benders_sequential/include/BendersSequential.h
  tests/CMakeLists.txt
  tests/end_to_end/examples/example_test.py
Labels: size/XL, tech

#397 Fix pytest warnings on marks
  tests/end_to_end/examples/pytest.ini
Labels: size/XS

#396 delete unused option: SLAVE_NUMBER
  conception/mergemps_out_example.json
  conception/out_merge.json
  conception/out_seq.json
  conception/output_example.schema.json
  conception/sequential_out_example.json
  data_test/mini_instance_INFEAS/options_default.txt
  data_test/mini_instance_LP/options_default.txt
  data_test/mini_instance_MIP/options_default.txt
  data_test/mini_instance_UNBOUNDED/options_default.txt
  data_test/mini_network/options_default.txt
  data_test/mini_network/options_weights.txt
  data_test/options_file/options_test.txt
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/SimulationOptions.cpp
  src/cpp/benders/benders_core/common.cpp
  src/cpp/benders/benders_core/include/SimulationOptions.hxx
  src/cpp/benders/benders_core/include/common.h
  src/cpp/benders/merge_mps/MergeMPS.cpp
  src/cpp/exe/benders_mpi/main.cpp
  src/python/antares_xpansion/xpansionConfig.py
  tests/cpp/helpers/JsonXpansionReaderTest.cc
Labels: size/L

#399 Feature/add xpress
  .github/workflows/centos7-system.yml
  .github/workflows/ubuntu-system.yml
  .github/workflows/windows-vcpkg.yml
  CMakeLists.txt
Labels: size/L

#402 Feature/new docker: use a bare docker (without deps download)
  .github/workflows/centos7-system.yml
  .github/workflows/ubuntu-system.yml
  docker/centos7-bare
Labels: size/M

#408 Feature/improve sensitivity logs
  data_test/sensitivity/benders_out.json
  data_test/sensitivity/sensitivity_in.json
  data_test/sensitivity/structure.txt
  docs/CHANGELOG.md
  src/cpp/exe/sensitivity/main.cpp
  src/cpp/sensitivity/Analysis.cpp
  src/cpp/sensitivity/Analysis.h
  src/cpp/sensitivity/SensitivityInputReader.cpp
  src/cpp/sensitivity/SensitivityLogger.cpp
  src/cpp/sensitivity/SensitivityStudy.cpp
  src/cpp/sensitivity/SensitivityWriter.cpp
  src/cpp/sensitivity/include/SensitivityInputReader.h
  src/cpp/sensitivity/include/SensitivityLogger.h
  src/cpp/sensitivity/include/SensitivityOutputData.h
  src/cpp/sensitivity/include/SensitivityWriter.h
  src/python/antares_xpansion/sensitivity_driver.py
  tests/cpp/sensitivity/CMakeLists.txt
  tests/cpp/sensitivity/SensitivityInputReaderTest.cpp
  tests/cpp/sensitivity/SensitivityLoggerTest.cpp
  tests/cpp/sensitivity/SensitivityPbModifierTest.cpp
  tests/cpp/sensitivity/SensitivityStudyTest.cpp
  tests/cpp/sensitivity/SensitivityWriterTest.cpp
Labels: size/XL

#411 Fix/end to end mpi tests
  .github/workflows/centos7-system.yml
  CMakeLists.txt
  docker/centos7-bare
  docs/developer-guide/install_from_sources/3-Build.md
  src/python/antares_xpansion/benders_driver.py
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/driver.py
  src/python/antares_xpansion/input_parser.py
  src/python/antares_xpansion/xpansionConfig.py
  tests/CMakeLists.txt
  tests/end_to_end/benders/conftest.py
  tests/end_to_end/benders/test_bendersEndToEnd.py
  tests/end_to_end/benders/test_bendersmpibendersEndToEnd.py
  tests/end_to_end/examples/conftest.py
  tests/end_to_end/examples/example_test.py
Labels: size/L

#405 Lpnamer: create MasterGeneration class
  src/cpp/exe/lpnamer/main.cpp
  src/cpp/lpnamer/problem_modifier/CMakeLists.txt
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.cpp
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.h
  src/cpp/lpnamer/problem_modifier/MasterGeneration.cpp
  src/cpp/lpnamer/problem_modifier/MasterGeneration.h
Labels: size/L

#417 delete method option in ini file && check
  data_test/examples/additionnal-constraints-binary/user/expansion/settings.ini
  data_test/examples/additionnal-constraints/user/expansion/settings.ini
  data_test/examples/empty-link-profile/user/expansion/settings.ini
  data_test/examples/hurdles-cost-profile-value-over-one/user/expansion/settings.ini
  data_test/examples/link-profile-with-empty-week/user/expansion/settings.ini
  data_test/examples/xpansion-test-01-hurdles-cost/user/expansion/settings.ini
  data_test/examples/xpansion-test-01-weights/user/expansion/settings.ini
  data_test/examples/xpansion-test-01/user/expansion/settings.ini
  data_test/examples/xpansion-test-02-new/user/expansion/settings.ini
  data_test/examples/xpansion-test-02/user/expansion/settings.ini
  data_test/examples/xpansion-test-03/user/expansion/settings.ini
  data_test/examples/xpansion-test-04-mps-rounding/user/expansion/settings.ini
  data_test/examples/xpansion-test-05-area-uppercase/user/expansion/settings.ini
  data_test/examples/xpansion-test-one-link-two-candidates/user/expansion/settings.ini
  data_test/test_case_7.1_structure/user/expansion/other_inputs_for_test/settings-1.ini
  data_test/test_case_7.1_structure/user/expansion/other_inputs_for_test/settings-2.ini
  data_test/test_case_7.1_structure/user/expansion/other_inputs_for_test/settings-3.ini
  data_test/test_case_7.1_structure/user/expansion/other_inputs_for_test/settings-accurate.ini
  data_test/test_case_7.1_structure/user/expansion/other_inputs_for_test/settings-error.ini
  data_test/test_case_7.1_structure/user/expansion/other_inputs_for_test/settings-fast.ini
  data_test/test_case_7.1_structure/user/expansion/other_inputs_for_test/settings-nonnumericgap.ini
  data_test/test_case_7.1_structure/user/expansion/other_inputs_for_test/settings-nottruefalse.ini
  data_test/test_case_7.1_structure/user/expansion/other_inputs_for_test/settings-relaxed_accurate.ini
  data_test/test_case_7.1_structure/user/expansion/other_inputs_for_test/settings-relaxed_fast.ini
  data_test/test_case_7.1_structure/user/expansion/other_inputs_for_test/settings-unknowncuttype.ini
  data_test/test_case_7.1_structure/user/expansion/other_inputs_for_test/settings-unknownopt.ini
  data_test/test_case_7.1_structure/user/expansion/settings.ini
  data_test/tests_lpnamer/tests_integer/test_lpnamer_01/user/expansion/settings.ini
  data_test/tests_lpnamer/tests_integer/test_one_link_one_candidate_1week/user/expansion/settings.ini
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_1week/user/expansion/settings.ini
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_simple_prob/user/expansion/settings.ini
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_simple_prob_hurdle_cost/user/expansion/settings.ini
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_simple_prob_null_profile/user/expansion/settings.ini
  data_test/tests_lpnamer/tests_relaxed/SmallTestSixCandidatesWithAlreadyInstalledCapacity-relaxed/user/expansion/settings.ini
  data_test/tests_lpnamer/tests_relaxed/test_one_link_one_candidate-relaxed/user/expansion/settings.ini
  examples/SmallTestFiveCandidates/user/expansion/settings.ini
  examples/SmallTestFiveCandidatesWithWeights/user/expansion/settings.ini
  examples/SmallTestSixCandidatesWithAlreadyInstalledCapacity/user/expansion/settings.ini
  examples/SmallTestSixCandidatesWithPlaylist/user/expansion/settings.ini
  examples/additionnal-constraints-binary/user/expansion/settings.ini
  examples/additionnal-constraints/user/expansion/settings.ini
  src/python/antares_xpansion/input_checker.py
  tests/python/test_input_checker.py
Labels: size/L

#421 Fix/windows ci
  .github/workflows/windows-vcpkg.yml
Labels: size/XS

#425 Reorganize tests
  tests/CMakeLists.txt
  tests/cpp/CMakeLists.txt
  tests/cpp/helpers/CMakeLists.txt
  tests/cpp/json_output_writer/CMakeLists.txt
Labels: size/L
