Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2022-02, with the labels that each got.

#365 Add summary of settings
  docs/user-guide/get-started/settings-definition.md
Labels: size/S

#357 allow to print solver's log in file
  docs/user-guide/get-started/settings-definition.md
  src/python/antares_xpansion/benders_driver.py
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/driver.py
  src/python/antares_xpansion/xpansionConfig.py
  tests/python/test_benders_driver.py
Labels: size/L

#367 Docs/typo correction
  docs/developer-guide/xpansion_steps/2-problem-modification.md
Labels: size/S

#368 remove useless files
  data_test/test_case_7.1_structure/user/expansion/report/20171108-1548_report.html
  data_test/test_case_7.1_structure/user/expansion/report/20171108-1648_report.html
Labels: size/XXL

#358 add userguide to zip archive
  .github/workflows/build-userguide.yml
  .github/workflows/generate-userguide-pdf/action.yml
  .github/workflows/releases-centos7.yml
  .github/workflows/releases-ubuntu.yml
  .github/workflows/releases-windows.yml
  .github/workflows/windows-vcpkg.yml
  CMakeLists.txt
Labels: documentation, size/L, tech

#370 remove unused parameters from antares settings.ini
  src/cpp/benders/benders_core/WorkerTrace.cpp
  src/cpp/benders/benders_core/include/WorkerTrace.h
  src/python/antares_xpansion/general_data_processor.py
  tests/cpp/solvers_interface/test_reading_problem.cpp
Labels: size/M

#343 refactor and add tests for input_checker.py
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/input_checker.py
  tests/python/test_input_checker.py
Labels: size/XL

#379 remove some includes in common.h
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/BendersStructsDatas.cpp
  src/cpp/benders/benders_core/CMakeLists.txt
  src/cpp/benders/benders_core/common.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/BendersStructsDatas.h
  src/cpp/benders/benders_core/include/Worker.h
  src/cpp/benders/benders_core/include/common.h
  src/cpp/benders/benders_mpi/include/BendersMPI.h
Labels: size/L

#380 print some options in out.json
  src/cpp/benders/output/JsonWriter.cpp
  src/cpp/benders/output/VoidWriter.cpp
  src/cpp/benders/output/include/JsonWriter.h
  src/cpp/benders/output/include/OutputWriter.h
  src/cpp/benders/output/include/VoidWriter.h
  src/cpp/exe/benders_mpi/main.cpp
  src/cpp/exe/benders_sequential/main.cpp
  tests/cpp/json_output_writer/output_writer_test.cpp
Labels: size/M
