Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2022-10, with the labels that each got.

#544 Fix issue with mishandling boolean represented as string
  src/python/antares_xpansion/general_data_processor.py
  src/python/antares_xpansion/general_data_reader.py
  tests/python/test_antares_driver.py
Labels: size/M

#491 Release 0.8.0
  .github/workflows/centos7-system-deps-build.yml
  .github/workflows/centos7-system.yml
  .github/workflows/windows-vcpkg-deps-build.yml
  .github/workflows/windows-vcpkg.yml
  CMakeLists.txt
  antares-version.json
  cmake/dependencies/CMakeLists.txt
  docs/CHANGELOG.md
  docs/assets/media/image17.png
  docs/assets/media/image18.png
  docs/user-guide/get-started/settings-definition.md
  sonar-project.properties
  src/cpp/lpnamer/model/ChronicleMapProvider.cpp
  src/python/antares_xpansion/candidates_reader.py
  src/python/antares_xpansion/chronicles_checker.py
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/general_data_processor.py
  src/python/antares_xpansion/general_data_reader.py
  src/python/antares_xpansion/input_checker.py
  tests/python/test_antares_driver.py
  tests/python/test_input_checker.py
Labels: size/XL

#545 change solver basis format to normal
  conception/Architecture_decision_records/Change_Solver_Basis_Format.md
  src/cpp/multisolver_interface/SolverCbc.cpp
  src/cpp/multisolver_interface/SolverClp.cpp
Labels: size/M

#547 Ci/fix develop
  .github/workflows/build-userguide.yml
  .github/workflows/build_centos7.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  .github/workflows/centos7-system-deps-build.yml
  .github/workflows/centos7-system.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-system-deps-build.yml
  .github/workflows/ubuntu-system.yml
  .github/workflows/windows-vcpkg-deps-build.yml
  .github/workflows/windows-vcpkg.yml
  .gitmodules
Labels: size/XL

#548 Protect "couplings" with mutex to prevent race condition during probl…
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.cpp
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.h
Labels: size/S

#552 Fix string formatting
  src/python/antares_xpansion/antares_driver.py
Labels: size/XS

#550 Fix concurrent upload of artifact
  .github/workflows/centos7-system.yml
  .github/workflows/ubuntu-system.yml
Labels: size/M

#554 Replace deprecated action reading json value
  .github/actions/read-json-value/action.yml
  .github/workflows/build-userguide.yml
  .github/workflows/build_centos7.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  .github/workflows/centos7-system-deps-build.yml
  .github/workflows/centos7-system.yml
  .github/workflows/generate-userguide-pdf/action.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-system-deps-build.yml
  .github/workflows/ubuntu-system.yml
  .github/workflows/windows-vcpkg-deps-build.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/L

#517 Feature/simulator8 3
  .github/workflows/build_centos7.yml
  .github/workflows/build_windows.yml
  .github/workflows/centos7-system.yml
  .github/workflows/download-extract-precompiled-libraries-tgz/action.yml
  .github/workflows/download-extract-precompiled-libraries-zip/action.yml
  .github/workflows/windows-vcpkg-deps-build.yml
  .github/workflows/windows-vcpkg.yml
  .gitmodules
  CMakeLists.txt
  antares-version.json
  conception/Architecture_decision_records/Xpress_env_in_actions.md
  docker/centos7
  src/cpp/benders/benders_mpi/CMakeLists.txt
  src/python/antares_xpansion/antares_driver.py
  src/python/antares_xpansion/driver.py
  src/python/antares_xpansion/general_data_processor.py
  src/python/antares_xpansion/study_output_cleaner.py
  src/python/antares_xpansion/xpansion_utils.py
  src/python/antares_xpansion/yearly_weight_writer.py
  tests/python/test_antares_driver.py
  tests/python/test_study_output_cleaner.py
  vcpkg_manifest/vcpkg.json
Labels: size/L

#562 Fix input checker for relaxed gap
  src/python/antares_xpansion/input_checker.py
Labels: bug, size/XS
