Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2022-12, with the labels that each got.

#570 Feature/simplify benders data structures
  src/cpp/benders/benders_by_batch/BatchCollection.cpp
  src/cpp/benders/benders_by_batch/BendersByBatch.cpp
  src/cpp/benders/benders_by_batch/CMakeLists.txt
  src/cpp/benders/benders_by_batch/include/BatchCollection.h
  src/cpp/benders/benders_by_batch/include/BendersByBatch.h
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/SubproblemCut.cpp
  src/cpp/benders/benders_core/WorkerMaster.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/BendersStructsDatas.h
  src/cpp/benders/benders_core/include/SubproblemCut.h
  src/cpp/benders/benders_core/include/WorkerMaster.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_mpi/include/BendersMPI.h
  src/cpp/benders/benders_sequential/BendersSequential.cpp
  src/cpp/benders/benders_sequential/include/BendersSequential.h
  src/cpp/exe/benders_mpi/main.cpp
  src/cpp/sensitivity/ProblemModifierCapex.cpp
  tests/cpp/benders/BendersByBatchTest.cpp
  tests/cpp/benders/benders_sequential_test.cpp
Labels: size/XL

#577 improve mpi efficiency
  src/cpp/benders/benders_mpi/BendersMPI.cpp
Labels: size/S

#576 Fix bug and remove useless print
  src/cpp/lpnamer/problem_modifier/LauncherHelpers.cpp
  src/cpp/lpnamer/problem_modifier/LauncherHelpers.h
  src/python/antares_xpansion/problem_generator_driver.py
  tests/cpp/lp_namer/AdditionalConstraintsTest.cc
Labels: size/M

#579 delete unused code
  src/python/antares_xpansion/config_loader.py
Labels: size/S

#580 Release/1.0.0 rc1
  CMakeLists.txt
  docs/user-guide/performance-history/performance-history.rst
Labels: size/XS

#582 delete print
  src/python/antares_xpansion/problem_generator_driver.py
Labels: size/XS

#587 Print PbGen logs
  src/cpp/benders/benders_core/include/Timer.h
  src/cpp/benders/benders_core/include/core/ILogger.h
  src/cpp/benders/logger/User.cpp
  src/cpp/benders/logger/UserFile.cpp
  src/cpp/exe/full_run/main.cpp
  src/cpp/helpers/CMakeLists.txt
  src/cpp/helpers/Timer.h
  src/cpp/lpnamer/helper/ProblemGenerationLogger.cpp
  src/cpp/lpnamer/main/RunProblemGeneration.cpp
  src/python/antares_xpansion/problem_generator_driver.py
Labels: size/L

#585 allow to work with unzipped mps after Pb Gen
  data_test/mini_instance_INFEAS/options_default.json
  data_test/mini_instance_LP/options_default.json
  data_test/mini_instance_LP/options_default_restart.json
  data_test/mini_instance_MIP/options_default.json
  data_test/mini_instance_MIP/options_default_restart.json
  data_test/mini_instance_UNBOUNDED/options_default.json
  data_test/mini_network/options_default.json
  data_test/mini_network/options_default_restart.json
  data_test/mini_network/options_weights.json
  data_test/mini_network/options_weights_restart.json
  src/cpp/benders/benders_core/SimulationOptions.cpp
  src/cpp/benders/benders_core/include/SimulationOptions.hxx
  src/cpp/benders/benders_core/include/common.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_sequential/BendersSequential.cpp
  src/cpp/benders/benders_sequential/include/BendersSequential.h
  src/cpp/exe/full_run/main.cpp
  src/cpp/exe/lpnamer/main.cpp
  src/cpp/helpers/ArchiveReader.cpp
  src/cpp/helpers/ArchiveReader.h
  src/cpp/helpers/ArchiveWriter.cpp
  src/cpp/helpers/ArchiveWriter.h
  src/cpp/lpnamer/main/ProblemGenerationExeOptions.cpp
  src/cpp/lpnamer/main/RunProblemGeneration.cpp
  src/cpp/lpnamer/main/include/ProblemGenerationExeOptions.h
  src/cpp/lpnamer/main/include/RunProblemGeneration.h
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.cpp
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.h
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/driver.py
  src/python/antares_xpansion/full_run_driver.py
  src/python/antares_xpansion/input_parser.py
  src/python/antares_xpansion/launcher_options_default_value.py
  src/python/antares_xpansion/launcher_options_keys.py
  src/python/antares_xpansion/optimisation_keys.py
  src/python/antares_xpansion/problem_generator_driver.py
  src/python/antares_xpansion/xpansionConfig.py
  tests/end_to_end/lpnamer/test_lpnamerEndToEnd.py
  tests/python/test_full_run_driver.py
  tests/python/test_input_parser.py
  tests/python/test_problem_generator_driver.py
Labels: size/L
