Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2022-11, with the labels that each got.

#486 ziplib adr
  conception/Architecture_decision_records/Zip_Lib.md
Labels: size/M

#561 Update default values and fix docs
  docs/CHANGELOG.md
  docs/user-guide/get-started/settings-definition.md
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/include/SimulationOptions.hxx
  src/python/antares_xpansion/xpansionConfig.py
  tests/cpp/logger/logger_test.cpp
Labels: size/M

#571 Upgrade simulator to 8.4
  antares-version.json
Labels: size/XS

#551 delete unused cplex related code
  CMakeLists.txt
  src/CMakeLists.txt
  src/cpp/multisolver_interface/CMakeLists.txt
  src/cpp/multisolver_interface/SolverCbc.cpp
  src/cpp/multisolver_interface/SolverClp.cpp
  src/cpp/multisolver_interface/SolverCplex.cpp
  src/cpp/multisolver_interface/SolverCplex.h
  src/cpp/multisolver_interface/SolverFactory.cpp
  src/cpp/multisolver_interface/SolverXpress.cpp
  src/cpp/multisolver_interface/include/multisolver_interface/SolverFactory.h
  src/python/antares_xpansion/xpansion_study_reader.py
  tests/python/test_xpansion_study_reader.py
Labels: size/XL
