Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2022-09, with the labels that each got.

#503 Feature/improve GitHub actions
  .github/workflows/build_centos7.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  .github/workflows/centos7-system-deps-build.yml
  .github/workflows/centos7-system.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-system-deps-build.yml
  .github/workflows/ubuntu-system.yml
  .github/workflows/windows-vcpkg-deps-build.yml
  .github/workflows/windows-vcpkg.yml
  sonar-project.properties
Labels: size/L

#513 Fix error in yml
  .github/workflows/ubuntu-system.yml
Labels: size/XS

#512 #508 Parallelize problem generation
  src/cpp/lpnamer/problem_modifier/CMakeLists.txt
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.cpp
Labels: size/S

#511 Force storenewset to true, fix chronicles_checker
  src/cpp/lpnamer/model/ChronicleMapProvider.cpp
  src/cpp/lpnamer/problem_modifier/LinkParametersCSVOverwriter.cpp
  src/python/antares_xpansion/candidates_reader.py
  src/python/antares_xpansion/chronicles_checker.py
  src/python/antares_xpansion/general_data_processor.py
  tests/python/test_antares_driver.py
Labels: size/L

#426 Feature/new directories constraints weights
  data_test/examples/additionnal-constraints-binary/user/expansion/constraints/contraintes_binaires.txt
  data_test/examples/additionnal-constraints/user/expansion/constraints/contraintes.txt
  data_test/examples/hurdles-cost-profile-value-over-one/user/expansion/constraints/contraintes.txt
  data_test/examples/xpansion-test-01-hurdles-cost/user/expansion/constraints/contraintes.txt
  data_test/examples/xpansion-test-01-hurdles-cost/user/expansion/constraints/contraintes_binaires.txt
  data_test/examples/xpansion-test-01-weights/user/expansion/constraints/contraintes.txt
  data_test/examples/xpansion-test-01-weights/user/expansion/constraints/contraintes_binaires.txt
  data_test/examples/xpansion-test-01-weights/user/expansion/weights/weights.txt
  data_test/examples/xpansion-test-01/user/expansion/constraints/contraintes.txt
  data_test/examples/xpansion-test-01/user/expansion/constraints/contraintes_binaires.txt
  data_test/examples/xpansion-test-03/user/expansion/constraints/contraintes.txt
  data_test/examples/xpansion-test-04-mps-rounding/user/expansion/constraints/contraintes.txt
  data_test/examples/xpansion-test-04-mps-rounding/user/expansion/constraints/contraintes_binaires.txt
  data_test/tests_lpnamer/tests_integer/test_lpnamer_01/user/expansion/constraints/contraintes.txt
  data_test/tests_lpnamer/tests_integer/test_lpnamer_01/user/expansion/constraints/contraintes_binaires.txt
  docs/user-guide/get-started/settings-definition.md
  examples/SmallTestFiveCandidates/user/expansion/constraints/contraintes.txt
  examples/SmallTestFiveCandidates/user/expansion/constraints/contraintes_binaires.txt
  examples/SmallTestFiveCandidatesWithWeights/user/expansion/constraints/contraintes.txt
  examples/SmallTestFiveCandidatesWithWeights/user/expansion/constraints/contraintes_binaires.txt
  examples/SmallTestFiveCandidatesWithWeights/user/expansion/weights/weights.txt
  examples/additionnal-constraints-binary/user/expansion/constraints/contraintes_binaires.txt
  examples/additionnal-constraints/user/expansion/constraints/contraintes.txt
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/xpansionConfig.py
Labels: size/S

#522 Fix/ntc error msg from release branch
  src/python/antares_xpansion/candidates_reader.py
  src/python/antares_xpansion/chronicles_checker.py
Labels: size/L

#524 Fix typos in docs
  docs/user-guide/optimization-principles/problem-formalization.md
Labels: size/XS

#507 Static in-out stabilization of the Benders algorithm
  data_test/examples/different_NTCs/user/expansion/settings.ini
  data_test/examples/hurdles-cost-profile-value-over-one/user/expansion/settings.ini
  data_test/examples/xpansion-test-02-new/user/expansion/settings.ini
  data_test/examples/xpansion-test-03/user/expansion/settings.ini
  docs/user-guide/get-started/settings-definition.md
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/BendersStructsDatas.cpp
  src/cpp/benders/benders_core/LastIterationReader.cpp
  src/cpp/benders/benders_core/LastIterationWriter.cpp
  src/cpp/benders/benders_core/SimulationOptions.cpp
  src/cpp/benders/benders_core/SubproblemCut.cpp
  src/cpp/benders/benders_core/WorkerMaster.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/BendersStructsDatas.h
  src/cpp/benders/benders_core/include/SimulationOptions.hxx
  src/cpp/benders/benders_core/include/SubproblemCut.h
  src/cpp/benders/benders_core/include/WorkerMaster.h
  src/cpp/benders/benders_core/include/common.h
  src/cpp/benders/benders_core/include/core/ILogger.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_sequential/BendersSequential.cpp
  src/cpp/benders/benders_sequential/include/BendersSequential.h
  src/cpp/benders/logger/CandidateLog.cpp
  src/cpp/benders/logger/IterationResultLog.cpp
  src/cpp/benders/logger/Master.cpp
  src/cpp/benders/logger/User.cpp
  src/cpp/benders/logger/UserFile.cpp
  src/cpp/benders/logger/include/logger/Master.h
  src/cpp/benders/logger/include/logger/User.h
  src/cpp/benders/logger/include/logger/UserFile.h
  src/cpp/lpnamer/model/ChronicleMapProvider.cpp
  src/cpp/lpnamer/problem_modifier/LinkParametersCSVOverwriter.cpp
  src/python/antares_xpansion/candidates_reader.py
  src/python/antares_xpansion/chronicles_checker.py
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/general_data_processor.py
  src/python/antares_xpansion/input_checker.py
  src/python/antares_xpansion/optimisation_keys.py
  src/python/antares_xpansion/xpansionConfig.py
  tests/cpp/TestDoubles/LoggerStub.h
  tests/cpp/benders/CMakeLists.txt
  tests/cpp/benders/benders_sequential_test.cpp
  tests/cpp/logger/logger_test.cpp
  tests/cpp/restart_benders/restart_lib_tests.cpp
  tests/end_to_end/examples/example_test.py
  tests/python/test_antares_driver.py
  tests/python/test_input_checker.py
Labels: optimization, size/XXL

#542 Revert to using std::vector for link profiles
  conception/Architecture_decision_records/LinkProfile_as_vector_instead_of_array.md
  src/cpp/lpnamer/model/LinkProfile.cpp
  src/cpp/lpnamer/model/LinkProfile.h
  tests/cpp/lp_namer/ActiveLinkTest.cpp
  tests/cpp/lp_namer/StudyUpdateTest.cc
Labels: size/L

#540 Properly set missing general data value to expected xpansion values
  src/python/antares_xpansion/general_data_processor.py
  tests/python/test_antares_driver.py
Labels: size/M

#529 Fix CentOS build dependencies workflow
  .github/workflows/centos7-system-deps-build.yml
Labels: size/S

#543 Playlist properly handled even with usage of ConfigParser
  src/python/antares_xpansion/general_data_processor.py
  src/python/antares_xpansion/general_data_reader.py
  tests/python/test_antares_driver.py
Labels: size/M
