Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2022-04, with the labels that each got.

#424 Update doc test table
  docs/developer-guide/install_from_sources/4-Tests.md
Labels: size/S

#416 Improve log format, add some tests
  src/cpp/benders/logger/include/Commons.h
  src/cpp/sensitivity/SensitivityInputReader.cpp
  src/cpp/sensitivity/SensitivityLogger.cpp
  src/cpp/sensitivity/include/SensitivityOutputData.h
  tests/cpp/sensitivity/SensitivityLoggerTest.cpp
  tests/cpp/sensitivity/SensitivityStudyTest.cpp
Labels: size/L

#431 fix sensitivity not showing error msg if no options provided--windows
  src/cpp/exe/sensitivity/main.cpp
Labels: size/M

#435 Feature/benders rename slave
  docs/user-guide/get-started/settings-definition.md
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/BendersStructsDatas.cpp
  src/cpp/benders/benders_core/CMakeLists.txt
  src/cpp/benders/benders_core/SimulationOptions.cpp
  src/cpp/benders/benders_core/SubproblemCut.cpp
  src/cpp/benders/benders_core/SubproblemWorker.cpp
  src/cpp/benders/benders_core/WorkerMaster.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/BendersStructsDatas.h
  src/cpp/benders/benders_core/include/SlaveCut.h
  src/cpp/benders/benders_core/include/SubproblemCut.h
  src/cpp/benders/benders_core/include/SubproblemWorker.h
  src/cpp/benders/benders_core/include/WorkerMaster.h
  src/cpp/benders/benders_core/include/WorkerSlave.h
  src/cpp/benders/benders_core/include/common.h
  src/cpp/benders/benders_core/include/core/ILogger.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_mpi/include/BendersMPI.h
  src/cpp/benders/benders_sequential/BendersSequential.cpp
  src/cpp/benders/logger/IterationResultLog.cpp
  src/cpp/benders/logger/User.cpp
  src/cpp/benders/logger/UserFile.cpp
  src/cpp/benders/merge_mps/MergeMPS.cpp
  src/cpp/sensitivity/Analysis.cpp
  src/cpp/sensitivity/Analysis.h
  tests/cpp/logger/logger_test.cpp
  tests/cpp/solvers_interface/test_exceptions.cpp
  tests/cpp/solvers_interface/test_modifying_problem.cpp
  tests/cpp/solvers_interface/test_solving_problem.cpp
Labels: size/XL

#436 Feature/benders seq parallel
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/CMakeLists.txt
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_mpi/include/BendersMPI.h
  src/cpp/benders/benders_sequential/include/BendersSequential.h
  src/cpp/sensitivity/SensitivityStudy.cpp
Labels: size/L

#437 use std::filesystem::path instead of custom Path or std::string : 1st
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/SimulationOptions.cpp
  src/cpp/benders/benders_core/SubproblemWorker.cpp
  src/cpp/benders/benders_core/Worker.cpp
  src/cpp/benders/benders_core/WorkerMaster.cpp
  src/cpp/benders/benders_core/common.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/SubproblemWorker.h
  src/cpp/benders/benders_core/include/Worker.h
  src/cpp/benders/benders_core/include/WorkerMaster.h
  src/cpp/benders/benders_core/include/common.h
  src/cpp/benders/factories/WriterFactories.cpp
  src/cpp/benders/factories/include/LoggerFactories.h
  src/cpp/benders/factories/include/WriterFactories.h
  src/cpp/benders/logger/UserFile.cpp
  src/cpp/benders/logger/include/logger/UserFile.h
  src/cpp/benders/merge_mps/MergeMPS.cpp
  src/cpp/benders/output/JsonWriter.cpp
  src/cpp/benders/output/include/JsonWriter.h
  src/cpp/exe/benders_mpi/main.cpp
  src/cpp/exe/benders_sequential/main.cpp
  src/cpp/exe/lpnamer/main.cpp
  src/cpp/exe/merge/main.cpp
  src/cpp/exe/sensitivity/main.cpp
  src/cpp/exe/study-updater/main.cpp
  src/cpp/helpers/include/helpers/Path.h
  src/cpp/lpnamer/input_reader/CandidatesINIReader.cpp
  src/cpp/lpnamer/input_reader/CandidatesINIReader.h
  src/cpp/lpnamer/input_reader/LinkProfileReader.cpp
  src/cpp/lpnamer/input_reader/LinkProfileReader.h
  src/cpp/lpnamer/problem_modifier/LauncherHelpers.cpp
  src/cpp/lpnamer/problem_modifier/LauncherHelpers.h
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.cpp
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.h
  src/cpp/lpnamer/problem_modifier/MasterGeneration.cpp
  src/cpp/lpnamer/problem_modifier/MasterGeneration.h
  src/cpp/lpnamer/problem_modifier/StudyUpdater.cpp
  src/cpp/lpnamer/problem_modifier/StudyUpdater.h
  src/cpp/multisolver_interface/SolverCbc.cpp
  src/cpp/multisolver_interface/SolverCbc.h
  src/cpp/multisolver_interface/SolverClp.cpp
  src/cpp/multisolver_interface/SolverClp.h
  src/cpp/multisolver_interface/SolverCplex.cpp
  src/cpp/multisolver_interface/SolverCplex.h
  src/cpp/multisolver_interface/SolverFactory.cpp
  src/cpp/multisolver_interface/SolverXpress.cpp
  src/cpp/multisolver_interface/SolverXpress.h
  src/cpp/multisolver_interface/include/multisolver_interface/SolverAbstract.h
  src/cpp/multisolver_interface/include/multisolver_interface/SolverFactory.h
  src/cpp/sensitivity/SensitivityFileLogger.cpp
  src/cpp/sensitivity/SensitivityWriter.cpp
  src/cpp/sensitivity/include/SensitivityFileLogger.h
  src/cpp/sensitivity/include/SensitivityWriter.h
  tests/cpp/json_output_writer/output_writer_test.cpp
  tests/cpp/logger/logger_test.cpp
  tests/cpp/lp_namer/LinkProfileReaderTest.cpp
  tests/cpp/lp_namer/StudyUpdateTest.cc
  tests/cpp/sensitivity/SensitivityWriterTest.cpp
  tests/cpp/solvers_interface/test_reading_problem.cpp
Labels: size/XXL

#439 Fix/option txt error
  data_test/mini_instance_INFEAS/options_default.json
  data_test/mini_instance_INFEAS/options_default.txt
  data_test/mini_instance_LP/options_default.json
  data_test/mini_instance_LP/options_default.txt
  data_test/mini_instance_MIP/options_default.json
  data_test/mini_instance_MIP/options_default.txt
  data_test/mini_instance_UNBOUNDED/options_default.json
  data_test/mini_instance_UNBOUNDED/options_default.txt
  data_test/mini_network/options_default.json
  data_test/mini_network/options_default.txt
  data_test/mini_network/options_weights.json
  data_test/mini_network/options_weights.txt
  src/cpp/benders/benders_core/CMakeLists.txt
  src/cpp/benders/benders_core/SimulationOptions.cpp
  src/cpp/benders/benders_core/include/SimulationOptions.h
  src/cpp/benders/benders_core/include/SimulationOptions.hxx
  src/python/antares_xpansion/benders_driver.py
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/driver.py
  src/python/antares_xpansion/xpansionConfig.py
  tests/end_to_end/benders/resultTest.json
  tests/python/test_antares_driver.py
  tests/python/test_benders_driver.py
Labels: size/L

#444 fix centos ci system libs build deps
  .github/workflows/centos7-system-deps-build.yml
Labels: size/XS

#448 Upgrade Antares to 8.1.1
  antares-version.json
Labels: size/XS
