Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2022-07, with the labels that each got.

#477 print warning msg if unused option is found in candidate.ini
  src/python/antares_xpansion/flushed_print.py
  src/python/antares_xpansion/input_checker.py
Labels: size/S

#476 Fix typos, formatting, and broken link fix
  docs/assets/media/candidate.PNG
  docs/assets/media/link_profile.PNG
  docs/developer-guide/xpansion_steps/1-antares-solver-problem.md
  docs/user-guide/get-started/candidate-definition.md
  docs/user-guide/get-started/prepare-a-simulation.md
  docs/user-guide/optimization-principles/problem-formalization.md
Labels: size/L

#481 manage case candidates with no capa files
  src/python/antares_xpansion/profile_link_checker.py
  tests/python/test_profile_link_checker.py
  tests/python/test_split_link_profile.py
Labels: size/S

#482 Fix/improve sensitivity log
  data_test/sensitivity/structure.txt
  docs/user-guide/get-started/sensitivity-analysis.md
  src/cpp/sensitivity/SensitivityFileLogger.cpp
  src/cpp/sensitivity/SensitivityInputReader.cpp
  src/cpp/sensitivity/SensitivityLogger.cpp
  src/cpp/sensitivity/SensitivityMasterLogger.cpp
  src/cpp/sensitivity/SensitivityStudy.cpp
  src/cpp/sensitivity/SensitivityWriter.cpp
  src/cpp/sensitivity/include/SensitivityFileLogger.h
  src/cpp/sensitivity/include/SensitivityILogger.h
  src/cpp/sensitivity/include/SensitivityInputReader.h
  src/cpp/sensitivity/include/SensitivityLogger.h
  src/cpp/sensitivity/include/SensitivityMasterLogger.h
  src/cpp/sensitivity/include/SensitivityOutputData.h
  src/cpp/sensitivity/include/SensitivityStudy.h
  src/cpp/sensitivity/include/SensitivityWriter.h
  tests/cpp/sensitivity/SensitivityInputReaderTest.cpp
  tests/cpp/sensitivity/SensitivityLoggerTest.cpp
  tests/cpp/sensitivity/SensitivityStudyTest.cpp
  tests/cpp/sensitivity/SensitivityWriterTest.cpp
Labels: size/L

#480 Feature/improve output json 2
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/LastIterationReader.cpp
  src/cpp/benders/benders_core/LastIterationWriter.cpp
  src/cpp/benders/benders_core/include/BendersStructsDatas.h
  src/cpp/benders/benders_core/include/core/ILogger.h
  src/cpp/benders/logger/User.cpp
  src/cpp/benders/logger/UserFile.cpp
  src/cpp/benders/output/JsonWriter.cpp
  src/cpp/benders/output/include/OutputWriter.h
  tests/cpp/json_output_writer/output_writer_test.cpp
  tests/cpp/logger/logger_test.cpp
  tests/cpp/restart_benders/restart_lib_tests.cpp
Labels: size/M

#461 Release/0.7.0
  .github/workflows/build-userguide.yml
  .github/workflows/centos7-system.yml
  .github/workflows/ubuntu-system.yml
  .github/workflows/windows-vcpkg.yml
  CMakeLists.txt
  antares-version.json
  data_test/sensitivity/structure.txt
  docs/user-guide/get-started/sensitivity-analysis.md
  src/cpp/multisolver_interface/SolverCbc.cpp
  src/cpp/multisolver_interface/SolverCbc.h
  src/cpp/multisolver_interface/SolverXpress.cpp
  src/cpp/multisolver_interface/include/multisolver_interface/SolverAbstract.h
  src/cpp/sensitivity/Analysis.cpp
  src/cpp/sensitivity/Analysis.h
  src/cpp/sensitivity/AnalysisFunctions.cpp
  src/cpp/sensitivity/AnalysisFunctions.h
  src/cpp/sensitivity/CMakeLists.txt
  src/cpp/sensitivity/SensitivityFileLogger.cpp
  src/cpp/sensitivity/SensitivityInputReader.cpp
  src/cpp/sensitivity/SensitivityLogger.cpp
  src/cpp/sensitivity/SensitivityMasterLogger.cpp
  src/cpp/sensitivity/SensitivityStudy.cpp
  src/cpp/sensitivity/SensitivityWriter.cpp
  src/cpp/sensitivity/include/SensitivityFileLogger.h
  src/cpp/sensitivity/include/SensitivityILogger.h
  src/cpp/sensitivity/include/SensitivityInputReader.h
  src/cpp/sensitivity/include/SensitivityLogger.h
  src/cpp/sensitivity/include/SensitivityMasterLogger.h
  src/cpp/sensitivity/include/SensitivityOutputData.h
  src/cpp/sensitivity/include/SensitivityStudy.h
  src/cpp/sensitivity/include/SensitivityWriter.h
  src/python/antares_xpansion/flushed_print.py
  src/python/antares_xpansion/input_checker.py
  src/python/antares_xpansion/sensitivity_driver.py
  tests/cpp/sensitivity/SensitivityInputReaderTest.cpp
  tests/cpp/sensitivity/SensitivityLoggerTest.cpp
  tests/cpp/sensitivity/SensitivityStudyTest.cpp
  tests/cpp/sensitivity/SensitivityWriterTest.cpp
  tests/cpp/solvers_interface/CMakeLists.txt
  tests/cpp/solvers_interface/test_basis.cpp
Labels: size/XL
