Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2022-05, with the labels that each got.

#452 Fix windows dependencies building
  .github/workflows/windows-vcpkg-deps-build.yml
Labels: size/XS

#453 Fix typos in the docs
  docs/user-guide/optimization-principles/problem-formalization.md
Labels: size/M

#443 Feature/improve error msg candidate ini
  src/python/antares_xpansion/input_checker.py
Labels: size/M

#441 Write optimal basis after Benders and use it for sensitivity
  data_test/sensitivity/real_basis.bss
  data_test/sensitivity/toy_basis.bss
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/CMakeLists.txt
  src/cpp/benders/benders_core/SimplexBasis.cpp
  src/cpp/benders/benders_core/SimulationOptions.cpp
  src/cpp/benders/benders_core/SubproblemWorker.cpp
  src/cpp/benders/benders_core/Worker.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/SimplexBasis.h
  src/cpp/benders/benders_core/include/SimulationOptions.hxx
  src/cpp/benders/benders_core/include/SubproblemWorker.h
  src/cpp/benders/benders_core/include/Worker.h
  src/cpp/benders/benders_core/include/common.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_sequential/BendersSequential.cpp
  src/cpp/exe/sensitivity/main.cpp
  src/cpp/multisolver_interface/SolverCbc.cpp
  src/cpp/multisolver_interface/SolverCbc.h
  src/cpp/multisolver_interface/SolverClp.cpp
  src/cpp/multisolver_interface/SolverClp.h
  src/cpp/multisolver_interface/SolverCplex.cpp
  src/cpp/multisolver_interface/SolverCplex.h
  src/cpp/multisolver_interface/SolverXpress.cpp
  src/cpp/multisolver_interface/SolverXpress.h
  src/cpp/multisolver_interface/include/multisolver_interface/SolverAbstract.h
  src/cpp/sensitivity/Analysis.cpp
  src/cpp/sensitivity/AnalysisFunctions.cpp
  src/cpp/sensitivity/AnalysisFunctions.h
  src/cpp/sensitivity/SensitivityInputReader.cpp
  src/cpp/sensitivity/SensitivityProblemModifier.cpp
  src/cpp/sensitivity/SensitivityStudy.cpp
  src/cpp/sensitivity/SensitivityWriter.cpp
  src/cpp/sensitivity/include/SensitivityInputReader.h
  src/cpp/sensitivity/include/SensitivityProblemModifier.h
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/driver.py
  src/python/antares_xpansion/sensitivity_driver.py
  src/python/antares_xpansion/xpansionConfig.py
  tests/cpp/sensitivity/SensitivityInputReaderTest.cpp
  tests/cpp/sensitivity/SensitivityStudyTest.cpp
  tests/cpp/sensitivity/SensitivityWriterTest.cpp
  tests/python/test_sensitivity_driver.py
Labels: size/XL
