Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2022-06, with the labels that each got.

#454 Fix test not running properly when buiding outside repository
  tests/cpp/sensitivity/CMakeLists.txt
  tests/cpp/sensitivity/SensitivityInputReaderTest.cpp
  tests/cpp/sensitivity/SensitivityPbModifierTest.cpp
  tests/cpp/sensitivity/SensitivityStudyTest.cpp
  tests/cpp/solvers_interface/CMakeLists.txt
  tests/cpp/solvers_interface/define_datas.cpp
Labels: size/M

#460 update change log
  docs/CHANGELOG.md
Labels: size/XS

#466 update ui
  src/python/antares-xpansion-ui.py
Labels: size/M

#469 Fix/write coin basis
  README.md
  src/cpp/multisolver_interface/SolverCbc.cpp
  src/cpp/multisolver_interface/SolverCbc.h
  src/cpp/multisolver_interface/SolverXpress.cpp
  src/cpp/multisolver_interface/include/multisolver_interface/SolverAbstract.h
  src/cpp/sensitivity/Analysis.cpp
  src/cpp/sensitivity/Analysis.h
  src/cpp/sensitivity/AnalysisFunctions.cpp
  src/cpp/sensitivity/AnalysisFunctions.h
  src/cpp/sensitivity/CMakeLists.txt
  src/cpp/sensitivity/SensitivityInputReader.cpp
  src/cpp/sensitivity/SensitivityStudy.cpp
  src/cpp/sensitivity/include/SensitivityInputReader.h
  src/python/antares_xpansion/sensitivity_driver.py
  tests/cpp/sensitivity/SensitivityStudyTest.cpp
  tests/cpp/solvers_interface/CMakeLists.txt
  tests/cpp/solvers_interface/test_basis.cpp
Labels: size/L
