Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2022-01, with the labels that each got.

#338 Docs/move log level
  docs/user-guide/get-started/settings-definition.md
Labels: size/S

#339 Conversion from str to int
  src/cpp/multisolver_interface/SolverXpress.cpp
  src/python/antares_xpansion/input_checker.py
Labels: size/XS

#342 fix centos7 ci -- force using psutil=5.8.0
  requirements.txt
Labels: size/XS

#349 Add timelimit to doc
  docs/user-guide/get-started/settings-definition.md
Labels: size/XS

#334 Feature/benders output writer
  src/cpp/CMakeLists.txt
  src/cpp/benders/CMakeLists.txt
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/CMakeLists.txt
  src/cpp/benders/benders_core/Clock.cpp
  src/cpp/benders/benders_core/JsonWriter.cpp
  src/cpp/benders/benders_core/VoidWriter.cpp
  src/cpp/benders/benders_core/WorkerTrace.cpp
  src/cpp/benders/benders_core/common.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/Clock.h
  src/cpp/benders/benders_core/include/JsonWriter.h
  src/cpp/benders/benders_core/include/OutputWriter.h
  src/cpp/benders/benders_core/include/VoidWriter.h
  src/cpp/benders/benders_core/include/common.h
  src/cpp/benders/benders_core/include/core/ILogger.h
  src/cpp/benders/benders_core/include/launcher.h
  src/cpp/benders/benders_core/launcher.cpp
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_mpi/include/BendersMPI.h
  src/cpp/benders/benders_mpi/include/launch_mpi.h
  src/cpp/benders/benders_mpi/launch_mpi.cpp
  src/cpp/benders/benders_sequential/Benders.cpp
  src/cpp/benders/benders_sequential/BendersSequential.cpp
  src/cpp/benders/benders_sequential/CMakeLists.txt
  src/cpp/benders/benders_sequential/SequentialLaunch.cpp
  src/cpp/benders/benders_sequential/include/Benders.h
  src/cpp/benders/benders_sequential/include/BendersSequential.h
  src/cpp/benders/benders_sequential/include/SequentialLaunch.h
  src/cpp/benders/factories/CMakeLists.txt
  src/cpp/benders/factories/LoggerFactories.cpp
  src/cpp/benders/factories/WriterFactories.cpp
  src/cpp/benders/factories/include/LoggerFactories.h
  src/cpp/benders/factories/include/WriterFactories.h
  src/cpp/benders/logger/CMakeLists.txt
  src/cpp/benders/logger/CandidateLog.cpp
  src/cpp/benders/logger/CandidateLog.h
  src/cpp/benders/logger/Commons.h
  src/cpp/benders/logger/IterationResultLog.cpp
  src/cpp/benders/logger/IterationResultLog.h
  src/cpp/benders/logger/Master.cpp
  src/cpp/benders/logger/User.cpp
  src/cpp/benders/logger/UserFile.cpp
  src/cpp/benders/logger/include/logger/Master.h
  src/cpp/benders/logger/include/logger/User.h
  src/cpp/benders/logger/include/logger/UserFile.h
  src/cpp/exe/benders_mpi/CMakeLists.txt
  src/cpp/exe/benders_mpi/main.cpp
  src/cpp/exe/benders_sequential/CMakeLists.txt
  src/cpp/exe/benders_sequential/main.cpp
  src/cpp/exe/merge/CMakeLists.txt
  src/cpp/exe/merge/merge_mps.cpp
  src/cpp/logger/User.cpp
  src/cpp/logger/include/logger/UserFile.h
  tests/cpp/CMakeLists.txt
  tests/cpp/json_output_writer/CMakeLists.txt
  tests/cpp/json_output_writer/output_writer_test.cpp
  tests/cpp/logger/logger_test.cpp
  tests/end_to_end/benders/resultTest.json
  tests/end_to_end/benders/test_bendersEndToEnd.py
Labels: size/XXL

#346 Correct extension for reportbenderssequential and lp_namer log file
  src/cpp/exe/benders_mpi/main.cpp
  src/cpp/exe/benders_sequential/main.cpp
  src/python/antares_xpansion/problem_generator_driver.py
  tests/python/test_problem_generator_driver.py
Labels: size/S

#354 delete unused dir media/
  media/AntaresSimulator_Logo.png
  media/simple-investments-candidates.png
Labels: size/XS

#352 delete unused benders options
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/BendersOptions.hxx
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/launcher.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_mpi/include/BendersMPI.h
  src/cpp/benders/benders_sequential/Benders.cpp
  src/cpp/benders/benders_sequential/BendersSequential.cpp
  src/cpp/benders/logger/IterationResultLog.cpp
  src/cpp/benders/logger/IterationResultLog.h
  src/python/antares_xpansion/xpansionConfig.py
  tests/cpp/json_output_writer/output_writer_test.cpp
Labels: size/XL

#353 Remove unnecessary timer
  src/cpp/multisolver_interface/SolverCbc.cpp
Labels: size/XS

#361 Make absence of numpy/pytest fatal
  tests/CMakeLists.txt
Labels: size/XS
