Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2023-10, with the labels that each got.

#692 Use Simulator 8.6.3
  antares-version.json
Labels: size/XS

#689 Update sonar properties to use server cache
  sonar-project.properties
Labels: size/XS

#687 Automatically release when a tag is pushed
  .github/workflows/centos-release.yml
  .github/workflows/release.yml
  .github/workflows/ubuntu-release.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/S

#693 Enable git227 and devtooset9 globaly (CentOS7 build deps)
  .github/workflows/centos7-system-deps-build.yml
Labels: size/S

#696 Ci/centos
  .github/workflows/build_centos7.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  .github/workflows/centos-release.yml
  .github/workflows/centos7-system-deps-build.yml
  .github/workflows/publish_centos_docker.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-release.yml
  .github/workflows/windows-vcpkg-deps-build.yml
  .github/workflows/windows-vcpkg.yml
  CMakeLists.txt
  docker/centos7
  docker/centos7-bare
  docker/centos7-system-deps
Labels: size/L

#697 fix mc-years bug --windows
  antares-version.json
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/SubproblemWorker.cpp
  src/cpp/benders/benders_core/Worker.cpp
  src/cpp/benders/benders_core/WorkerMaster.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/SubproblemWorker.h
  src/cpp/benders/benders_core/include/Worker.h
  src/cpp/benders/benders_core/include/WorkerMaster.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_sequential/BendersSequential.cpp
  src/cpp/benders/factories/BendersFactory.cpp
  src/cpp/benders/logger/UserFile.cpp
  src/cpp/lpnamer/main/RunProblemGeneration.cpp
  src/cpp/lpnamer/problem_modifier/AntaresProblemToXpansionProblemTranslator.cpp
  src/cpp/lpnamer/problem_modifier/AntaresProblemToXpansionProblemTranslator.h
  src/cpp/lpnamer/problem_modifier/IProblemProviderPort.h
  src/cpp/lpnamer/problem_modifier/IXpansionProblemsProvider.h
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.cpp
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.h
  src/cpp/lpnamer/problem_modifier/MPSFileProblemProviderAdapter.cpp
  src/cpp/lpnamer/problem_modifier/MPSFileProblemProviderAdapter.h
  src/cpp/lpnamer/problem_modifier/MasterGeneration.cpp
  src/cpp/lpnamer/problem_modifier/MasterGeneration.h
  src/cpp/lpnamer/problem_modifier/MasterProblemBuilder.cpp
  src/cpp/lpnamer/problem_modifier/MasterProblemBuilder.h
  src/cpp/lpnamer/problem_modifier/XpansionProblemsFromAntaresProvider.cpp
  src/cpp/lpnamer/problem_modifier/XpansionProblemsFromAntaresProvider.h
  src/cpp/lpnamer/problem_modifier/ZipProblemProviderAdapter.cpp
  src/cpp/lpnamer/problem_modifier/ZipProblemProviderAdapter.h
  src/cpp/lpnamer/problem_modifier/ZipProblemsProviderAdapter.cpp
  src/cpp/lpnamer/problem_modifier/ZipProblemsProviderAdapter.h
  src/cpp/multisolver_interface/SolverCbc.cpp
  src/cpp/multisolver_interface/SolverCbc.h
  src/cpp/multisolver_interface/SolverClp.cpp
  src/cpp/multisolver_interface/SolverClp.h
  src/cpp/multisolver_interface/SolverFactory.cpp
  src/cpp/multisolver_interface/SolverXpress.cpp
  src/cpp/multisolver_interface/SolverXpress.h
  src/cpp/multisolver_interface/include/multisolver_interface/SolverAbstract.h
  src/cpp/multisolver_interface/include/multisolver_interface/SolverFactory.h
  src/python/antares_xpansion/__version__.py.in
  src/python/antares_xpansion/antares_driver.py
  src/python/antares_xpansion/config_loader.py
  tests/cpp/benders/benders_sequential_test.cpp
  tests/cpp/lp_namer/MasterProblemBuilderTest.cpp
  tests/cpp/sensitivity/SensitivityPbModifierTest.cpp
  tests/cpp/sensitivity/SensitivityStudyTest.cpp
  tests/python/test_antares_driver.py
Labels: bug, size/L

#681 candidates parsing issues
  src/cpp/lpnamer/input_reader/CandidatesINIReader.cpp
  src/cpp/lpnamer/input_reader/CandidatesINIReader.h
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/input_checker.py
Labels: size/M
