Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2023-02, with the labels that each got.

#616 Update version to 1.0.3-rc1
  CMakeLists.txt
Labels: size/XS

#619 delete benderssequential
  data_test/mini_instance_LP/README.md
  data_test/mini_instance_MIP/README.md
  data_test/mini_network/README.md
  docs/developer-guide/xpansion_steps/0-overview.md
  src/CMakeLists.txt
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/factories/BendersFactory.cpp
  src/cpp/benders/factories/include/BendersFactory.h
  src/cpp/exe/CMakeLists.txt
  src/cpp/exe/benders/CMakeLists.txt
  src/cpp/exe/benders/main.cpp
  src/cpp/exe/benders_sequential/CMakeLists.txt
  src/cpp/exe/benders_sequential/main.cpp
  src/cpp/full_run/FullRunOptionsParser.cpp
  src/cpp/full_run/include/FullRunOptionsParser.h
  src/python/antares_xpansion/benders_driver.py
  src/python/antares_xpansion/config_file_parser.py
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/driver.py
  src/python/antares_xpansion/full_run_driver.py
  src/python/antares_xpansion/input_parser.py
  src/python/antares_xpansion/launcher_options_default_value.py
  src/python/antares_xpansion/resume_study.py
  src/python/antares_xpansion/xpansionConfig.py
  src/python/config.yaml.in
  tests/cpp/full_run/FullRunTest.cpp
  tests/end_to_end/benders/README.md
  tests/end_to_end/benders/pytest.ini
  tests/end_to_end/benders/test_bendersEndToEnd.py
  tests/end_to_end/benders/test_bendersSequentialEndToEnd.py
  tests/end_to_end/benders/test_bendersmpibendersEndToEnd.py
  tests/end_to_end/examples/example_test.py
  tests/end_to_end/restart/README.md
  tests/end_to_end/restart/pytest.ini
  tests/end_to_end/restart/test_restartBendersEndToEnd.py
  tests/end_to_end/restart/test_restartBendersSequentialEndToEnd.py
  tests/end_to_end/restart/test_restartBendersmpibendersEndToEnd.py
  tests/python/test_benders_driver.py
  tests/python/test_config_file_parser.py
  tests/python/test_full_run_driver.py
  tests/python/test_resume_study.py
Labels: size/L

#602 Get rid of mps.txt
  src/cpp/lpnamer/input_reader/MpsTxtWriter.cpp
  src/cpp/lpnamer/input_reader/MpsTxtWriter.h
  src/cpp/lpnamer/main/RunProblemGeneration.cpp
  src/cpp/lpnamer/main/include/RunProblemGeneration.h
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.cpp
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.h
  tests/cpp/lp_namer/MpsTxtWriterTest.cpp
Labels: size/L

#623 Dipatch action to publish docker image
  .github/workflows/publish_centos_docker.yml
Labels: size/S

#627 Install git from third party package
  docker/centos7-bare
Labels: size/XS
