Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2023-11, with the labels that each got.

#710 Create lp directories in cpp
  conception/SequenceDiagrams/FileManipulation/diagram.svg
  conception/SequenceDiagrams/FileManipulation/diagram.txt
  src/cpp/exe/lpnamer/main.cpp
  src/cpp/lpnamer/helper/ProblemGenerationLogger.cpp
  src/cpp/lpnamer/main/RunProblemGeneration.cpp
  src/python/antares_xpansion/full_run_driver.py
  src/python/antares_xpansion/problem_generator_driver.py
  tests/cpp/lp_namer/CMakeLists.txt
  tests/cpp/lp_namer/ProblemGenerationTest.cpp
  tests/python/test_problem_generator_driver.py
Labels: size/XL

#711 deploy doxygen code documentation
  .github/workflows/doxygen.yml
  .nojekyll
  README.md
  docs/Doxyfile
  docs/antares-xpansion.patch
  docs/developer-guide/install_from_sources/0-INSTALL.md
Labels: size/XXL

#716 Fix doc compilation
  readthedocs.yml
Labels: size/XS

#718 Release/1.2.1
  CMakeLists.txt
  antares-version.json
  docs/changelog/CHANGELOG.md
  docs/user-guide/performance-history/perf-graphs.ipynb
  docs/user-guide/performance-history/perf_data.json
  sonar-project.properties
Labels: size/M

#722 Fix gap contribution bug
  src/cpp/benders/benders_by_batch/BendersByBatch.cpp
Labels: size/XS
