Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2023-03, with the labels that each got.

#629 Add actions for merge queue
  .github/workflows/build_centos7.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
Labels: size/XS

#621 Feature/benders-by-batch-with-mpi
  data_test/examples/additionnal-constraints-binary/user/expansion/settings_by_batch.ini
  data_test/examples/additionnal-constraints/user/expansion/settings_by_batch.ini
  data_test/examples/empty-link-profile/user/expansion/settings_by_batch.ini
  data_test/examples/hurdles-cost-profile-value-over-one/user/expansion/settings_by_batch.ini
  data_test/examples/link-profile-with-empty-week/user/expansion/settings_by_batch.ini
  data_test/examples/xpansion-test-01-hurdles-cost/user/expansion/settings_by_batch.ini
  data_test/examples/xpansion-test-01-weights/user/expansion/settings_by_batch.ini
  data_test/examples/xpansion-test-01/user/expansion/settings_by_batch.ini
  data_test/examples/xpansion-test-03/user/expansion/settings_by_batch.ini
  data_test/examples/xpansion-test-04-mps-rounding/user/expansion/settings_by_batch.ini
  data_test/examples/xpansion-test-one-link-two-candidates/user/expansion/settings_by_batch.ini
  docs/developer-guide/install_from_sources/4-Tests.md
  src/cpp/benders/benders_by_batch/BatchCollection.cpp
  src/cpp/benders/benders_by_batch/BendersByBatch.cpp
  src/cpp/benders/benders_by_batch/CMakeLists.txt
  src/cpp/benders/benders_by_batch/include/BatchCollection.h
  src/cpp/benders/benders_by_batch/include/BendersByBatch.h
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/BendersStructsDatas.h
  src/cpp/benders/benders_core/include/core/ILogger.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_mpi/include/BendersMPI.h
  src/cpp/benders/benders_mpi/include/common_mpi.h
  src/cpp/benders/benders_sequential/BendersSequential.cpp
  src/cpp/benders/benders_sequential/include/BendersSequential.h
  src/cpp/benders/factories/BendersFactory.cpp
  src/cpp/benders/factories/LoggerFactories.cpp
  src/cpp/benders/factories/include/BendersFactory.h
  src/cpp/benders/logger/Master.cpp
  src/cpp/benders/logger/User.cpp
  src/cpp/benders/logger/UserFile.cpp
  src/cpp/benders/logger/include/logger/Master.h
  src/cpp/benders/logger/include/logger/User.h
  src/cpp/benders/logger/include/logger/UserFile.h
  src/cpp/exe/benders_by_batch/main.cpp
  src/cpp/exe/full_run/main.cpp
  src/python/antares_xpansion/full_run_driver.py
  tests/CMakeLists.txt
  tests/cpp/TestDoubles/LoggerStub.h
  tests/cpp/benders/BendersByBatchTest.cpp
  tests/cpp/benders/benders_sequential_test.cpp
  tests/cpp/logger/logger_test.cpp
  tests/end_to_end/examples/example_test.py
  tests/end_to_end/examples/pytest.ini
Labels: size/XL

#628 remove deprecated code
  src/cpp/exe/full_run/main.cpp
  src/cpp/exe/lpnamer/main.cpp
  src/cpp/lpnamer/main/ProblemGenerationExeOptions.cpp
  src/cpp/lpnamer/main/RunProblemGeneration.cpp
  src/cpp/lpnamer/main/include/ProblemGenerationExeOptions.h
  src/cpp/lpnamer/main/include/RunProblemGeneration.h
  src/cpp/lpnamer/problem_modifier/AntaresProblemToXpansionProblemTranslator.cpp
  src/cpp/lpnamer/problem_modifier/AntaresProblemToXpansionProblemTranslator.h
  src/cpp/lpnamer/problem_modifier/ArchiveProblemWriter.cpp
  src/cpp/lpnamer/problem_modifier/ArchiveProblemWriter.h
  src/cpp/lpnamer/problem_modifier/CMakeLists.txt
  src/cpp/lpnamer/problem_modifier/IProblemProviderPort.h
  src/cpp/lpnamer/problem_modifier/IXpansionProblemsProvider.h
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.cpp
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.h
  src/cpp/lpnamer/problem_modifier/MPSFileProblemProviderAdapter.cpp
  src/cpp/lpnamer/problem_modifier/MPSFileProblemProviderAdapter.h
  src/cpp/lpnamer/problem_modifier/MPSFileWriter.cpp
  src/cpp/lpnamer/problem_modifier/MPSFileWriter.h
  src/cpp/lpnamer/problem_modifier/XpansionProblemsFromAntaresProvider.cpp
  src/cpp/lpnamer/problem_modifier/XpansionProblemsFromAntaresProvider.h
  src/cpp/lpnamer/problem_modifier/ZipProblemProviderAdapter.cpp
  src/cpp/lpnamer/problem_modifier/ZipProblemProviderAdapter.h
  src/cpp/lpnamer/problem_modifier/ZipProblemsProviderAdapter.cpp
  src/cpp/lpnamer/problem_modifier/ZipProblemsProviderAdapter.h
  src/python/antares_xpansion/optimisation_keys.py
  src/python/antares_xpansion/xpansionConfig.py
  tests/cpp/benders/benders_sequential_test.cpp
  tests/end_to_end/lpnamer/test_lpnamerEndToEnd.py
Labels: size/L

#633 Update xpress tag to 8.13
  .github/workflows/build_centos7.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  .github/workflows/centos7-system.yml
  .github/workflows/ubuntu-system.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/S

#630 1.0.3 simulation name
  .github/workflows/build_centos7.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  .github/workflows/centos7-system.yml
  .github/workflows/download-extract-precompiled-libraries-tgz/action.yml
  .github/workflows/publish_centos_docker.yml
  .github/workflows/ubuntu-system.yml
  .github/workflows/windows-vcpkg.yml
  docker/centos7-bare
  docs/CHANGELOG.md
  docs/user-guide/get-started/launching-optimization.md
  docs/user-guide/get-started/sensitivity-analysis.md
  src/python/antares_xpansion/config_loader.py
Labels: size/M

#637 Fix filename
  src/cpp/benders/benders_core/Worker.cpp
Labels: size/S

#639 print user and host names
  src/python/antares_xpansion/log_utils.py
  src/python/launch.py
Labels: size/S
