Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2023-01, with the labels that each got.

#597 upgrade to antares 8.4.1
  CMakeLists.txt
  antares-version.json
Labels: size/XS

#598 Update clean
  src/cpp/helpers/AntaresArchiveUpdater.cpp
Labels: size/S

#594 improve logs
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/logger/User.cpp
  src/cpp/benders/logger/UserFile.cpp
  src/cpp/benders/output/include/OutputWriter.h
  src/python/launch.py
  tests/cpp/logger/logger_test.cpp
Labels: size/S

#595 Feature/export-parts-of-pb-gen-driver-to-cpp
  data_test/mps_zip/archive2.zip
  data_test/tests_lpnamer/LpFilesExtractor/2_areas_files.zip
  data_test/tests_lpnamer/LpFilesExtractor/3_intercos_files.zip
  data_test/tests_lpnamer/LpFilesExtractor/empty_archive.zip
  data_test/tests_lpnamer/LpFilesExtractor/test_0_interco_1_area.zip
  data_test/tests_lpnamer/MpsTxtWriterTest/MpsTxtWriterTest_CheckMpsTxtContent.zip
  src/cpp/exe/full_run/main.cpp
  src/cpp/exe/lpnamer/main.cpp
  src/cpp/exe/study-updater/main.cpp
  src/cpp/helpers/ArchiveIO.h
  src/cpp/helpers/ArchiveReader.cpp
  src/cpp/helpers/ArchiveReader.h
  src/cpp/helpers/ArchiveWriter.cpp
  src/cpp/helpers/ArchiveWriter.h
  src/cpp/lpnamer/helper/common_lpnamer.h
  src/cpp/lpnamer/input_reader/CMakeLists.txt
  src/cpp/lpnamer/input_reader/GeneralDataReader.cpp
  src/cpp/lpnamer/input_reader/GeneralDataReader.h
  src/cpp/lpnamer/input_reader/LpFilesExtractor.cpp
  src/cpp/lpnamer/input_reader/LpFilesExtractor.h
  src/cpp/lpnamer/input_reader/MpsTxtWriter.cpp
  src/cpp/lpnamer/input_reader/MpsTxtWriter.h
  src/cpp/lpnamer/input_reader/WeightsFileReader.cpp
  src/cpp/lpnamer/input_reader/WeightsFileReader.h
  src/cpp/lpnamer/input_reader/WeightsFileWriter.cpp
  src/cpp/lpnamer/input_reader/WeightsFileWriter.h
  src/cpp/lpnamer/main/ProblemGenerationExeOptions.cpp
  src/cpp/lpnamer/main/RunProblemGeneration.cpp
  src/cpp/lpnamer/main/include/ProblemGenerationExeOptions.h
  src/cpp/lpnamer/main/include/RunProblemGeneration.h
  src/cpp/lpnamer/problem_modifier/LauncherHelpers.cpp
  src/cpp/lpnamer/problem_modifier/LauncherHelpers.h
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.cpp
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.h
  src/cpp/study-updater/StudyUpdateRunner.cpp
  src/cpp/study-updater/include/StudyUpdateRunner.h
  src/python/antares_xpansion/full_run_driver.py
  src/python/antares_xpansion/problem_generator_driver.py
  tests/cpp/lp_namer/CMakeLists.txt
  tests/cpp/lp_namer/LpFilesExtractorTest.cpp
  tests/cpp/lp_namer/MpsTxtWriterTest.cpp
  tests/cpp/lp_namer/WeightsFileReaderTest.cpp
  tests/cpp/zip_mps/zip_mps_lib_tests.cpp
  tests/end_to_end/lpnamer/test_lpnamerEndToEnd.py
  tests/python/test_problem_generator_driver.py
Labels: size/XXL

#563 v1.0.0
  CMakeLists.txt
  antares-version.json
  docs/CHANGELOG.md
  docs/user-guide/get-started/settings-definition.md
  docs/user-guide/performance-history/perf-graphs.ipynb
  docs/user-guide/performance-history/perf_data.json
  docs/user-guide/performance-history/performance-history.rst
  docs/user-guide/performance-history/performance.py
  mkdocs.yml
  requirements-doc.txt
  sonar-project.properties
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/include/SimulationOptions.hxx
  src/cpp/lpnamer/problem_modifier/LauncherHelpers.cpp
  src/cpp/lpnamer/problem_modifier/LauncherHelpers.h
  src/python/antares_xpansion/general_data_processor.py
  tests/cpp/logger/logger_test.cpp
  tests/cpp/lp_namer/AdditionalConstraintsTest.cc
  tests/python/test_antares_driver.py
Labels: size/XL

#592 create benders factories
  src/cpp/CMakeLists.txt
  src/cpp/benders/benders_mpi/BendersMpiMain.cpp
  src/cpp/benders/benders_mpi/CMakeLists.txt
  src/cpp/benders/benders_mpi/include/BendersMPI.h
  src/cpp/benders/benders_mpi/include/BendersMpiMain.h
  src/cpp/benders/benders_sequential/BendersSequentialMain.cpp
  src/cpp/benders/benders_sequential/CMakeLists.txt
  src/cpp/benders/benders_sequential/include/BendersSequentialMain.h
  src/cpp/benders/factories/BendersFactory.cpp
  src/cpp/benders/factories/CMakeLists.txt
  src/cpp/benders/factories/include/BendersFactory.h
  src/cpp/exe/benders_by_batch/main.cpp
  src/cpp/exe/benders_mpi/CMakeLists.txt
  src/cpp/exe/benders_mpi/main.cpp
  src/cpp/exe/benders_sequential/CMakeLists.txt
  src/cpp/exe/benders_sequential/main.cpp
  src/cpp/exe/full_run/CMakeLists.txt
  src/cpp/exe/full_run/main.cpp
  src/cpp/full_run/CMakeLists.txt
  src/cpp/full_run/FullRunOptionsParser.cpp
  src/cpp/full_run/include/FullRunOptionsParser.h
  tests/cpp/CMakeLists.txt
  tests/cpp/full_run/CMakeLists.txt
  tests/cpp/full_run/FullRunTest.cpp
Labels: size/XL

#605 Update docs
  docs/user-guide/performance-history/perf_data.json
  docs/user-guide/performance-history/performance.py
Labels: size/S

#606 Merge pull request #605 from AntaresSimulatorTeam/fix/update_docs
  docs/user-guide/performance-history/perf_data.json
  docs/user-guide/performance-history/performance.py
Labels: size/S

#604 Feature/expand-bendersmpi-2
  .github/workflows/build_centos7.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  .github/workflows/centos7-system-deps-build.yml
  .github/workflows/centos7-system.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-system-deps-build.yml
  .github/workflows/ubuntu-system.yml
  .github/workflows/windows-vcpkg-deps-build.yml
  .github/workflows/windows-vcpkg.yml
  CMakeLists.txt
  docs/developer-guide/install_from_sources/3-Build.md
  src/CMakeLists.txt
  src/cpp/CMakeLists.txt
  src/cpp/benders/CMakeLists.txt
  src/cpp/benders/benders_mpi/CMakeLists.txt
  src/cpp/benders/benders_mpi/include/BendersMPI.h
  src/cpp/benders/factories/BendersFactory.cpp
  src/cpp/benders/factories/CMakeLists.txt
  src/cpp/benders/factories/include/BendersFactory.h
  src/cpp/exe/CMakeLists.txt
  src/cpp/exe/benders_mpi/CMakeLists.txt
  src/cpp/exe/full_run/CMakeLists.txt
  src/cpp/exe/full_run/main.cpp
  tests/cpp/CMakeLists.txt
  tests/cpp/full_run/CMakeLists.txt
  tests/cpp/helpers/CMakeLists.txt
  tests/cpp/lp_namer/CMakeLists.txt
Labels: size/L

#609 Feature/use-bendersmpi-with-1-proc
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/factories/BendersFactory.cpp
  src/python/antares_xpansion/input_parser.py
  src/python/antares_xpansion/launcher_options_default_value.py
  tests/CMakeLists.txt
  tests/end_to_end/benders/test_bendersEndToEnd.py
  tests/end_to_end/benders/test_bendersSequentialEndToEnd.py
  tests/end_to_end/examples/example_test.py
Labels: size/M

#610 Update docs
  docs/CHANGELOG.md
Labels: size/XS

#613 Update graphs
  docs/user-guide/performance-history/perf-graphs.ipynb
  docs/user-guide/performance-history/perf_data.json
  docs/user-guide/performance-history/performance.py
Labels: size/L
