Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2023-12, with the labels that each got.

#725 Update Build doc to include --target install command
  docs/developer-guide/install_from_sources/3-Build.md
Labels: size/XS, 🍉 Safe to Merge

#728 fix windows full build
  src/cpp/multisolver_interface/environment.cc
Labels: size/S, 👀 Take a deeper dive

#729 merge fork change
  docs/user-guide/get-started/settings-definition.md
  src/cpp/benders/benders_by_batch/BendersByBatch.cpp
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/BendersMathLogger.cpp
  src/cpp/benders/benders_core/SimulationOptions.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/BendersMathLogger.h
  src/cpp/benders/benders_core/include/BendersStructsDatas.h
  src/cpp/benders/benders_core/include/SimulationOptions.hxx
  src/cpp/benders/benders_core/include/common.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_mpi/include/BendersMPI.h
  src/cpp/benders/factories/BendersFactory.cpp
  src/cpp/benders/factories/include/LoggerFactories.h
  src/cpp/benders/logger/Master.cpp
  src/cpp/benders/logger/MathLogger.cpp
  src/cpp/benders/logger/User.cpp
  src/cpp/benders/logger/UserFile.cpp
  src/cpp/benders/logger/include/logger/Master.h
  src/cpp/benders/logger/include/logger/MathLogger.h
  src/cpp/benders/logger/include/logger/User.h
  src/cpp/benders/logger/include/logger/UserFile.h
  src/cpp/xpansion_interfaces/ILogger.h
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/input_checker.py
  src/python/antares_xpansion/optimisation_keys.py
  src/python/antares_xpansion/xpansionConfig.py
  tests/cpp/TestDoubles/LoggerStub.h
  tests/cpp/logger/logger_test.cpp
Labels: size/XL, 🍉 Safe to Merge

#731 Clean subproblem cut data structures
  src/cpp/benders/benders_core/CMakeLists.txt
  src/cpp/benders/benders_core/SubproblemCut.cpp
  src/cpp/benders/benders_core/WorkerMaster.cpp
  src/cpp/benders/benders_core/include/SubproblemCut.h
Labels: size/L, 🍉 Safe to Merge

#733 solver logs: one file per proc
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/factories/BendersFactory.cpp
  src/cpp/multisolver_interface/SolverXpress.cpp
  src/cpp/multisolver_interface/environment.cc
  tests/cpp/benders/benders_sequential_test.cpp
Labels: size/M, 👀 Take a deeper dive
