Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2023-04, with the labels that each got.

#647 Fix/merge-release1.0.3-in-develop
  data_test/mini_instance_INFEAS/options_default.json
  docs/user-guide/get-started/launching-optimization.md
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_sequential/include/BendersSequential.h
  src/cpp/helpers/AntaresArchiveUpdater.cpp
  src/cpp/helpers/ArchiveReader.cpp
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.h
  src/python/antares_xpansion/input_parser.py
  src/python/antares_xpansion/launcher_options_default_value.py
  src/python/antares_xpansion/launcher_options_keys.py
  src/python/antares_xpansion/xpansionConfig.py
  tests/python/test_input_parser.py
Labels: size/M

#644 fix trace file
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  tests/cpp/benders/benders_sequential_test.cpp
Labels: size/XS

#645 incomplete trace file in benders by batch
  src/cpp/benders/benders_by_batch/BendersByBatch.cpp
Labels: size/XS

#642 fix expansion bug
  src/cpp/benders/output/JsonWriter.cpp
Labels: size/XS

#638 fix tests
  data_test/mini_instance_INFEAS/options_default.json
  data_test/mini_instance_INFEAS/structure.txt
  data_test/mini_instance_UNBOUNDED/options_default.json
  src/cpp/benders/benders_by_batch/BendersByBatch.cpp
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/StartUp.cpp
  src/cpp/benders/benders_core/Worker.cpp
  src/cpp/benders/benders_core/include/Worker.h
  src/cpp/benders/factories/BendersFactory.cpp
  src/cpp/benders/output/JsonWriter.cpp
  src/cpp/benders/output/VoidWriter.cpp
  src/cpp/benders/output/include/JsonWriter.h
  src/cpp/benders/output/include/VoidWriter.h
  src/cpp/xpansion_interfaces/OutputWriter.h
  tests/CMakeLists.txt
  tests/cpp/TestDoubles/WriterStub.h
  tests/cpp/json_output_writer/output_writer_test.cpp
  tests/cpp/restart_benders/restart_lib_tests.cpp
  tests/end_to_end/benders/conftest.py
  tests/end_to_end/benders/resultTest.json
  tests/end_to_end/benders/test_bendersEndToEnd.py
  tests/end_to_end/benders/test_bendersSequentialEndToEnd.py
  tests/end_to_end/benders/test_bendersmpibendersEndToEnd.py
Labels: size/L

#649 fix develop
  src/cpp/benders/benders_by_batch/BendersByBatch.cpp
  src/cpp/benders/benders_core/BendersBase.cpp
  tests/end_to_end/examples/pytest.ini
Labels: size/S

#652 Update docs
  docs/changelog/CHANGELOG.md
  docs/changelog/format_changes.md
  docs/index.md
  docs/user-guide/benders.bib
  docs/user-guide/get-started/launching-optimization.md
  docs/user-guide/get-started/settings-definition.md
  docs/user-guide/optimization-principles/optimization-principles.rst
  docs/user-guide/optimization-principles/problem-formalization.md
  docs/user-guide/performance-history/performance-history.rst
  mkdocs.yml
  requirements-doc.txt
Labels: size/L

#650 Fix display in csv logs
  src/cpp/benders/benders_core/BendersBase.cpp
Labels: size/XS

#654 Add how-to for the docs
  docs/how_to.md
Labels: size/S

#653 benders by batch trace file
  src/cpp/benders/benders_by_batch/BendersByBatch.cpp
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
Labels: size/XS

#655 Install boost library
  CMakeLists.txt
Labels: size/S

#656 fix centos ci compilation
  .github/workflows/build_centos7.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  .github/workflows/centos7-system-deps-build.yml
  .github/workflows/centos7-system.yml
  .github/workflows/compile-boost/action.yml
  .github/workflows/compile-tbb/action.yml
  .github/workflows/download-extract-precompiled-libraries-tgz/action.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-system-deps-build.yml
  .github/workflows/ubuntu-system.yml
  docker/centos7
  docker/centos7-bare
Labels: size/L
