Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2024-06, with the labels that each got.

#837 Remove centos full build with dependence workflow
  .github/workflows/centos7-system-deps-build.yml
Labels: size/L

#841 fix c char* whitespace
  src/cpp/multisolver_interface/environment.cc
Labels: size/XS

#842 fix truncated xpress path on linux
  src/cpp/multisolver_interface/environment.cc
Labels: size/XS

#849 Fix missing version number in assets
  .github/workflows/build_centos7.yml
  .github/workflows/build_windows.yml
Labels: size/S

#846 Update Antares Simulator to 9.1.0
  .github/workflows/build_oracle8.yml
  antares-version.json
Labels: size/XS

#851 Remove TBB dependency
  .github/workflows/build_centos7.yml
  .github/workflows/build_oracle8.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  .github/workflows/compile-tbb/action.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-system-deps-build.yml
  .github/workflows/windows-vcpkg-deps-build.yml
  docs/developer-guide/install_from_sources/2-Dependencies-install.md
  src/cpp/benders/benders_core/CMakeLists.txt
  src/cpp/lpnamer/problem_modifier/CMakeLists.txt
  src/cpp/sensitivity/CMakeLists.txt
Labels: size/M

#854 Fix vcpkg caching issues
  .github/workflows/build_centos7.yml
  .github/workflows/build_oracle8.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-system-deps-build.yml
  .github/workflows/windows-vcpkg-deps-build.yml
Labels: size/S
