Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2024-10, with the labels that each got.

#933 Update to or-tools-rte 9.11-rte1.1
  .github/workflows/build_centos7.yml
  .github/workflows/build_oracle8.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  .github/workflows/sonarcloud.yml
Labels: size/M

#936 Use vcpkg registry for custom ports
  ports/coin-or-cbc/portfile.cmake
  ports/coin-or-cbc/vcpkg.json
  ports/coin-or-cgl/portfile.cmake
  ports/coin-or-cgl/vcpkg.json
  ports/coin-or-clp/portfile.cmake
  ports/coin-or-clp/vcpkg.json
  ports/coin-or-osi/portfile.cmake
  ports/coin-or-osi/vcpkg.json
  ports/coinutils/portfile.cmake
  ports/coinutils/vcpkg.json
  vcpkg-configuration.json
  vcpkg.json
Labels: size/L

#852 Remove unnecessary gtest install by system package manager
  .github/workflows/sonarcloud.yml
Labels: size/XS

#940 Handle Antares error -9
  src/python/antares_xpansion/antares_driver.py
Labels: size/XS

#938 Move uuid to ports
  .github/workflows/build_centos7.yml
  .github/workflows/build_oracle8.yml
  .github/workflows/publish_centos_docker.yml
  docker/centos7-system-deps
  vcpkg.json
Labels: size/S

#942 add doc on how to use Xpress
  docs/developer-guide/install_from_sources/0-INSTALL.md
  docs/developer-guide/install_from_sources/3-Build.md
  docs/developer-guide/install_from_sources/7-Xpress.md
Labels: size/L

#943 print git sha1
  CMakeLists.txt
  src/python/antares_xpansion/__version__.py.in
  src/python/antares_xpansion/input_parser.py
  src/python/launch.py
Labels: size/S

#945 criterions.txt is removed by the archive cleaner
  src/cpp/benders/benders_mpi/BendersMpiOuterLoop.cpp
Labels: size/XS

#944 Fix generation of weights in API mode [ANT-2196]
  src/cpp/lpnamer/input_reader/WeightsFileWriter.cpp
  src/cpp/lpnamer/input_reader/WeightsFileWriter.h
  src/cpp/lpnamer/main/ProblemGeneration.cpp
  src/cpp/lpnamer/main/include/ProblemGeneration.h
  tests/cpp/lp_namer/CMakeLists.txt
  tests/cpp/lp_namer/WeightsFileWriterTest.cpp
  tests/end_to_end/cucumber/features/weights.feature
  tests/end_to_end/cucumber/steps/steps.py
Labels: size/L

#949 add Iteration Num
  src/cpp/benders/benders_core/include/BendersMathLogger.h
Labels: size/XS

#954 Fix/conflict feature clean cmake
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/BendersMathLogger.h
Labels: size/XS

#953 trigger only by push
  .github/workflows/build_centos7.yml
  .github/workflows/build_oracle8.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  .github/workflows/sonarcloud.yml
Labels: size/M

#952 Fix weights test
  tests/end_to_end/cucumber/features/weights.feature
Labels: size/XS

#950 Avoid computing max criterion when there is none
  .github/workflows/cucumber-tests/action.yml
  data_test/mini_instance_MIP/adequacy_criterion.yml
  src/cpp/benders/benders_mpi/BendersMpiOuterLoop.cpp
  tests/end_to_end/cucumber/features/outer_loop_tests.feature
  tests/end_to_end/cucumber/steps/steps.py
Labels: size/L

#941 ANT-2223
  src/cpp/benders/benders_by_batch/BendersByBatch.cpp
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/BendersMathLogger.cpp
  src/cpp/benders/benders_core/CMakeLists.txt
  src/cpp/benders/benders_core/CriterionComputation.cpp
  src/cpp/benders/benders_core/OuterLoopInputDataReader.cpp
  src/cpp/benders/benders_core/SubproblemWorker.cpp
  src/cpp/benders/benders_core/VariablesGroup.cpp
  src/cpp/benders/benders_core/common.cpp
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/BendersBase.h
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/CriterionComputation.h
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/OuterLoopInputDataReader.h
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/VariablesGroup.h
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/common.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_mpi/BendersMpiOuterLoop.cpp
  src/cpp/benders/benders_mpi/OuterLoopBenders.cpp
  src/cpp/benders/benders_mpi/include/antares-xpansion/benders/benders_mpi/BendersMPI.h
  src/cpp/benders/benders_mpi/include/antares-xpansion/benders/benders_mpi/BendersMpiOuterLoop.h
  src/cpp/benders/benders_mpi/include/antares-xpansion/benders/benders_mpi/OuterLoopBenders.h
  src/cpp/benders/factories/BendersFactory.cpp
  src/cpp/benders/factories/include/antares-xpansion/benders/factories/BendersFactory.h
  src/cpp/benders/outer_loop/CMakeLists.txt
  src/cpp/benders/outer_loop/OuterLoop.cpp
  src/cpp/benders/outer_loop/OuterLoopBiLevel.cpp
  src/cpp/benders/outer_loop/include/antares-xpansion/benders/outer_loop/CriterionComputation.h
  src/cpp/benders/outer_loop/include/antares-xpansion/benders/outer_loop/OuterLoop.h
  src/cpp/benders/outer_loop/include/antares-xpansion/benders/outer_loop/OuterLoopBiLevel.h
  src/cpp/xpansion_interfaces/include/antares-xpansion/xpansion_interfaces/ILogger.h
  tests/cpp/outer_loop/outer_loop_test.cpp
Labels: size/XL

#956 Increment variable names every week
  src/cpp/lpnamer/model/Problem.cpp
  src/cpp/lpnamer/model/ProblemNameParser.cpp
  src/cpp/lpnamer/model/include/antares-xpansion/lpnamer/model/Problem.h
  src/cpp/lpnamer/model/include/antares-xpansion/lpnamer/model/ProblemNameParser.h
  src/cpp/lpnamer/problem_modifier/AntaresProblemToXpansionProblemTranslator.cpp
  src/cpp/lpnamer/problem_modifier/ProblemVariablesFromProblemAdapter.cpp
  src/python/antares_xpansion/antares_driver.py
  tests/cpp/lp_namer/CMakeLists.txt
  tests/cpp/lp_namer/ProblemConstructionTest.cpp
  tests/cpp/lp_namer/ProblemVariablesFromProblemAdapterTest.cpp
  tests/python/test_antares_driver.py
Labels: size/L

#955 [Ant-2223] use area file
  src/cpp/benders/benders_by_batch/BatchCollection.cpp
  src/cpp/benders/benders_core/BendersMathLogger.cpp
  src/cpp/benders/benders_core/SimulationOptions.cpp
  src/cpp/benders/benders_core/WorkerMaster.cpp
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/BendersMathLogger.h
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/OuterLoopInputDataReader.h
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/SimulationOptions.hxx
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/common.h
  src/cpp/benders/benders_mpi/include/antares-xpansion/benders/benders_mpi/BendersMPI.h
  src/cpp/benders/factories/BendersFactory.cpp
  src/cpp/benders/factories/include/antares-xpansion/benders/factories/BendersFactory.h
  src/cpp/benders/logger/Master.cpp
  src/cpp/benders/logger/MathLogger.cpp
  src/cpp/benders/logger/User.cpp
  src/cpp/benders/logger/UserFile.cpp
  src/cpp/benders/logger/include/antares-xpansion/benders/logger/Master.h
  src/cpp/benders/logger/include/antares-xpansion/benders/logger/MathLogger.h
  src/cpp/benders/logger/include/antares-xpansion/benders/logger/User.h
  src/cpp/benders/logger/include/antares-xpansion/benders/logger/UserFile.h
  src/cpp/benders/output/include/antares-xpansion/benders/output/JsonWriter.h
  src/cpp/helpers/AreaParser.cpp
  src/cpp/helpers/CMakeLists.txt
  src/cpp/helpers/Clock.cpp
  src/cpp/helpers/include/antares-xpansion/helpers/AreaParser.h
  src/cpp/lpnamer/helper/ProblemGenerationLogger.cpp
  src/cpp/lpnamer/helper/include/antares-xpansion/lpnamer/helper/ProblemGenerationLogger.h
  src/cpp/lpnamer/input_reader/CandidatesINIReader.cpp
  src/cpp/lpnamer/input_reader/include/antares-xpansion/lpnamer/input_reader/CandidatesINIReader.h
  src/cpp/xpansion_interfaces/CMakeLists.txt
  src/cpp/xpansion_interfaces/include/antares-xpansion/xpansion_interfaces/Clock.h
  src/cpp/xpansion_interfaces/include/antares-xpansion/xpansion_interfaces/ILogger.h
  src/cpp/xpansion_interfaces/include/antares-xpansion/xpansion_interfaces/LoggerUtils.h
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/optimisation_keys.py
  src/python/antares_xpansion/xpansionConfig.py
  tests/cpp/TestDoubles/LoggerStub.h
  tests/cpp/logger/logger_test.cpp
  tests/cpp/lp_namer/CandidatesINIReaderTest.cpp
Labels: size/L

#957 Fix/area file full steps
  src/cpp/exe/full_run/main.cpp
Labels: size/XS

#960 use only area file in Benders
  src/cpp/benders/factories/BendersFactory.cpp
Labels: size/XS

#947 Target to generate graph
  CMakeGraphVizOptions.cmake
  CMakeLists.txt
Labels: size/S
