Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2024-08, with the labels that each got.

#883 update changelog
  docs/changelog/CHANGELOG.md
  docs/user-guide/get-started/adequacy-criterion.md
Labels: size/XS

#881 v1.3.2
  CMakeLists.txt
  antares-version.json
  docs/changelog/CHANGELOG.md
  sonar-project.properties
  vcpkg.json
Labels: size/S

#895 Remove unnecessary dependency
  ports/coinutils/vcpkg.json
Labels: size/XS

#886 Test assets are running in fresh environnement (Ubuntu)
  .github/workflows/build_ubuntu.yml
Labels: size/M

#878 [ANT-1912] Make Outer loop lib independant from Benders
  data_test/external_loop_test/lp/master_last_basis.bss
  docs/user-guide/get-started/launching-optimization.md
  docs/user-guide/get-started/settings-definition.md
  src/cpp/benders/benders_by_batch/BendersByBatch.cpp
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/BendersMathLogger.cpp
  src/cpp/benders/benders_core/CMakeLists.txt
  src/cpp/benders/benders_core/CutsManagement.cpp
  src/cpp/benders/benders_core/MasterUpdateBase.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/BendersMathLogger.h
  src/cpp/benders/benders_core/include/CutsManagement.h
  src/cpp/benders/benders_core/include/MasterUpdate.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_mpi/BendersMpiOuterLoop.cpp
  src/cpp/benders/benders_mpi/CMakeLists.txt
  src/cpp/benders/benders_mpi/OuterLoopBenders.cpp
  src/cpp/benders/benders_mpi/include/BendersMPI.h
  src/cpp/benders/benders_mpi/include/BendersMpiOuterLoop.h
  src/cpp/benders/benders_mpi/include/OuterLoopBenders.h
  src/cpp/benders/benders_sequential/include/BendersSequential.h
  src/cpp/benders/factories/BendersFactory.cpp
  src/cpp/benders/factories/include/BendersFactory.h
  src/cpp/benders/logger/include/logger/MathLogger.h
  src/cpp/benders/outer_loop/CMakeLists.txt
  src/cpp/benders/outer_loop/CriterionComputation.cpp
  src/cpp/benders/outer_loop/OuterLoop.cpp
  src/cpp/benders/outer_loop/OuterLoopBiLevel.cpp
  src/cpp/benders/outer_loop/OuterLoopInputDataReader.cpp
  src/cpp/benders/outer_loop/VariablesGroup.cpp
  src/cpp/benders/outer_loop/include/CriterionComputation.h
  src/cpp/benders/outer_loop/include/IMasterUpdate.h
  src/cpp/benders/outer_loop/include/OuterLoop.h
  src/cpp/benders/outer_loop/include/OuterLoopBiLevel.h
  src/cpp/benders/outer_loop/include/OuterLoopInputDataReader.h
  src/cpp/benders/outer_loop/include/VariablesGroup.h
  tests/cpp/outer_loop/outer_loop_test.cpp
Labels: size/XXL

#899 Number ADR for easiest referencing/discussion
  conception/Architecture_decision_records/[000]Use_ADR.md
  conception/Architecture_decision_records/[001] Split_MPS_files.md
  conception/Architecture_decision_records/[002] MPI_or_multithreading.md
  conception/Architecture_decision_records/[003] Change_Solver_Basis_Format.md
  conception/Architecture_decision_records/[004] LinkProfile_as_vector_instead_of_array.md
  conception/Architecture_decision_records/[005] Xpress_env_in_actions.md
  conception/Architecture_decision_records/[006] Zip_Lib.md
  conception/Architecture_decision_records/[007] Portable_Xpansion_Windows.md
  conception/Architecture_decision_records/[008] Subproblem_data_storage_for_outer_loop.md
  conception/Architecture_decision_records/[009] Install_jsoncpp.md
  conception/Architecture_decision_records/[010] Create_custom_vcpkg_ports_for_deps.md
Labels: size/S

#897 Test assets are running in fresh environnement (Windows)
  .github/workflows/build_windows.yml
Labels: size/M

#902 Update documentation
  docs/developer-guide/install_from_sources/0-INSTALL.md
  docs/developer-guide/install_from_sources/1-Development-requirements.md
  docs/developer-guide/install_from_sources/2-Dependencies-install.md
  docs/developer-guide/install_from_sources/3-Build.md
  docs/developer-guide/install_from_sources/4-Tests.md
  docs/user-guide/get-started/installation.md
  mkdocs.yml
Labels: size/L
