Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2024-11, with the labels that each got.

#958 add tests
  .github/workflows/build_centos7.yml
  .github/workflows/build_oracle8.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  examples/SmallTestFiveCandidatesWithWeights/output/.gitkeep
  src/cpp/benders/benders_core/BendersMathLogger.cpp
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/BendersMathLogger.h
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/BendersStructsDatas.h
  tests/cpp/logger/logger_test.cpp
  tests/end_to_end/cucumber/__init__.py
  tests/end_to_end/cucumber/features/Benders_criterion_output_tests.feature
  tests/end_to_end/cucumber/features/__init__.py
  tests/end_to_end/cucumber/features/environment.py
  tests/end_to_end/cucumber/features/steps/__init__.py
  tests/end_to_end/cucumber/features/steps/steps.py
  tests/end_to_end/cucumber/features/weights.feature
  tests/end_to_end/cucumber/steps/steps.py
  tests/end_to_end/examples/example_test.py
  tests/end_to_end/utils_functions.py
Labels: size/XL

#961 Update antares solver to 9.2-rc5
  .github/workflows/build_windows.yml
  antares-version.json
  docs/developer-guide/install_from_sources/2-Dependencies-install.md
  src/python/antares_xpansion/problem_generator_driver.py
  tests/end_to_end/cucumber/features/steps/steps.py
  tests/end_to_end/lpnamer/test_lpnamerEndToEnd.py
  tests/end_to_end/utils_functions.py
Labels: size/S

#967 Fix compile issues on Ubuntu 22
  CMakeLists.txt
  src/cpp/benders/benders_core/CMakeLists.txt
  src/cpp/exe/full_run/CMakeLists.txt
  src/cpp/lpnamer/problem_modifier/CMakeLists.txt
  tests/cpp/solvers_interface/catch2.hpp
Labels: size/XXL

#948 Move json reader where it is used
  src/cpp/helpers/CMakeLists.txt
  src/cpp/study-updater/CMakeLists.txt
  src/cpp/study-updater/JsonXpansionReader.cpp
  src/cpp/study-updater/LinkParametersCSVOverwriter.cpp
  src/cpp/study-updater/StudyUpdater.cpp
  src/cpp/study-updater/private/JsonXpansionReader.h
  tests/cpp/CMakeLists.txt
  tests/cpp/helpers/CMakeLists.txt
  tests/cpp/helpers/JsonXpansionReaderTest.cc
  tests/cpp/study_updater/CMakeLists.txt
  tests/cpp/study_updater/JsonXpansionReaderTest.cc
Labels: size/L
