Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2024-01, with the labels that each got.

#719 print low level logs
  cmake/dependencies/CMakeLists.txt
  docs/user-guide/get-started/settings-definition.md
  src/cpp/benders/benders_by_batch/BendersByBatch.cpp
  src/cpp/benders/benders_by_batch/include/BendersByBatch.h
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/BendersMathLogger.cpp
  src/cpp/benders/benders_core/BendersStructsDatas.cpp
  src/cpp/benders/benders_core/CMakeLists.txt
  src/cpp/benders/benders_core/SimulationOptions.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/BendersMathLogger.h
  src/cpp/benders/benders_core/include/BendersStructsDatas.h
  src/cpp/benders/benders_core/include/SimulationOptions.hxx
  src/cpp/benders/benders_core/include/common.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_mpi/include/BendersMPI.h
  src/cpp/benders/benders_sequential/BendersSequential.cpp
  src/cpp/benders/benders_sequential/include/BendersSequential.h
  src/cpp/benders/factories/BendersFactory.cpp
  src/cpp/benders/factories/include/BendersFactory.h
  src/cpp/benders/factories/include/LoggerFactories.h
  src/cpp/benders/logger/CMakeLists.txt
  src/cpp/benders/logger/Master.cpp
  src/cpp/benders/logger/MathLogger.cpp
  src/cpp/benders/logger/User.cpp
  src/cpp/benders/logger/UserFile.cpp
  src/cpp/benders/logger/include/logger/Master.h
  src/cpp/benders/logger/include/logger/MathLogger.h
  src/cpp/benders/logger/include/logger/User.h
  src/cpp/benders/logger/include/logger/UserFile.h
  src/cpp/multisolver_interface/SolverCbc.cpp
  src/cpp/multisolver_interface/SolverClp.cpp
  src/cpp/multisolver_interface/SolverXpress.cpp
  src/cpp/multisolver_interface/environment.cc
  src/cpp/multisolver_interface/include/multisolver_interface/environment.h
  src/cpp/xpansion_interfaces/ILogger.h
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/input_checker.py
  tests/cpp/TestDoubles/LoggerStub.h
  tests/cpp/benders/benders_sequential_test.cpp
  tests/cpp/logger/logger_test.cpp
  tests/cpp/tests_utils/RandomDirGenerator.cpp
Labels: size/XXL, 🚨 Don't Merge

#740 Feature/cpp20
  .github/workflows/build_centos7.yml
  .github/workflows/build_ubuntu.yml
  CMakeLists.txt
  docker/centos7-system-deps
  src/cpp/helpers/FileInBuffer.cpp
Labels: size/S

#741 Update to devtoolset-10 properly
  .github/workflows/centos-release.yml
  .github/workflows/centos7-system-deps-build.yml
  docs/developer-guide/install_from_sources/1-Development-requirements.md
  docs/developer-guide/install_from_sources/3-Build.md
Labels: size/S

#743 Update badges
  docs/index.md
Labels: size/S

#664 Oracle8 build
  .github/workflows/build_oracle8.yml
  .github/workflows/compile-boost/action.yml
  .github/workflows/compile-tbb/action.yml
  antares-version.json
  requirements.txt
Labels: size/L

#746 Fix upload assets
  .github/workflows/centos-release.yml
  .github/workflows/ubuntu-release.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/S

#744 remove wrong prefix path
  cmake/dependencies/CMakeLists.txt
Labels: size/XS

#747 Oracle8 cpp20 support
  .github/workflows/build_oracle8.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/compile-boost/action.yml
  .github/workflows/compile-tbb/action.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-release.yml
  .github/workflows/ubuntu-system-deps-build.yml
Labels: size/S

#749 Update badges link in developer guide
  docs/developer-guide/install_from_sources/0-INSTALL.md
Labels: size/S

#752 Replace INSTANTIATE_TEST_CASE_P by INSTANTIATE_TEST_SUITE_P
  .github/workflows/build_centos7.yml
  .github/workflows/compile-gtest/action.yml
  tests/cpp/full_run/FullRunTest.cpp
  tests/cpp/lp_namer/ProblemConstructionTest.cpp
Labels: size/S

#754 Build gtest in centOS
  .github/workflows/centos-release.yml
  .github/workflows/centos7-system-deps-build.yml
Labels: size/XS
