Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2024-04, with the labels that each got.

#773 Fix sonar
  .github/workflows/sonarcloud.yml
  sonar-project.properties
Labels: size/M

#785 fix single file name
  .github/workflows/windows-vcpkg.yml
Labels: size/XS

#771 fix xpress detection spam
  src/cpp/benders/benders_core/Worker.cpp
  src/cpp/benders/benders_core/include/BendersMathLogger.h
  src/cpp/lpnamer/helper/ProblemGenerationLogger.cpp
  src/cpp/lpnamer/helper/ProblemGenerationLogger.h
  src/cpp/lpnamer/main/ProblemGeneration.cpp
  src/cpp/multisolver_interface/SolverCbc.cpp
  src/cpp/multisolver_interface/SolverClp.cpp
  src/cpp/multisolver_interface/SolverFactory.cpp
  src/cpp/multisolver_interface/SolverXpress.cpp
  src/cpp/multisolver_interface/environment.cc
  src/cpp/multisolver_interface/include/multisolver_interface/SolverFactory.h
  src/cpp/multisolver_interface/include/multisolver_interface/environment.h
  src/cpp/xpansion_interfaces/ILogger.h
  tests/cpp/ext_loop/ext_loop_test.cpp
  tests/cpp/sensitivity/SensitivityStudyTest.cpp
Labels: size/L

#786 Feature/embed mpi
  CMakeLists.txt
  conception/Architecture_decision_records/Portable_Xpansion_Windows.md
  src/python/antares_xpansion/benders_driver.py
  src/python/antares_xpansion/config_file_parser.py
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/driver.py
  src/python/antares_xpansion/xpansionConfig.py
  src/python/config.yaml.in
  tests/python/test_benders_driver.py
Labels: size/L

#787 [ANT-1461] sensitivity study with unzipped outputs
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/full_run_driver.py
Labels: size/S

#796 [CMAKE] Remove macro jsoncpplib_name, use variable instead
  CMakeLists.txt
  src/cpp/benders/benders_core/CMakeLists.txt
  src/cpp/benders/output/CMakeLists.txt
  src/cpp/helpers/CMakeLists.txt
  tests/cpp/helpers/CMakeLists.txt
Labels: size/M

#798 Remove XPRESS_ROOT from cmake arguments (unused)
  .github/workflows/build_centos7.yml
  .github/workflows/build_oracle8.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  .github/workflows/centos-release.yml
  .github/workflows/ol8-release.yml
  .github/workflows/ubuntu-release.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/S
