Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2024-09, with the labels that each got.

#909 fix dangling ref
  src/cpp/benders/outer_loop/OuterLoopInputDataReader.cpp
  src/cpp/benders/outer_loop/include/OuterLoopInputDataReader.h
Labels: size/XS

#918 Remove extra files
  examples/SmallTestFiveCandidates/logs/solver-20210414-162528.log
  examples/SmallTestFiveCandidates/logs/solver-20210414-162650.log
  examples/SmallTestFiveCandidates/output/README.txt
Labels: size/XXL

#917 Prevent concurrent access during close and delete of archive
  src/cpp/helpers/ArchiveWriter.cpp
  src/cpp/helpers/ArchiveWriter.h
Labels: size/M

#916 Prevent unnecessary string copy
  src/cpp/lpnamer/model/ActiveLinks.cpp
  src/cpp/lpnamer/model/ActiveLinks.h
  src/cpp/lpnamer/problem_modifier/ProblemVariablesFromProblemAdapter.cpp
Labels: size/S

#915 Properly link to xpress loader even is coin is disabled
  src/cpp/multisolver_interface/CMakeLists.txt
  src/cpp/multisolver_interface/environment.cc
  src/cpp/multisolver_interface/include/multisolver_interface/dynamic_library.h
  src/cpp/multisolver_interface/include/multisolver_interface/environment.h
Labels: size/S

#911 Use devtoolset 11 for CentOS
  .github/workflows/build_centos7.yml
  .github/workflows/publish_centos_docker.yml
  docker/centos7-system-deps
  src/cpp/helpers/ArchiveReader.cpp
  src/cpp/helpers/ArchiveWriter.cpp
Labels: size/M

#913 Use toolset 11 for OL8
  .github/workflows/build_centos7.yml
  .github/workflows/build_oracle8.yml
Labels: size/S

#921 transforming --allow_run_as_root into boolean
  CMakeLists.txt
  tests/CMakeLists.txt
  tests/end_to_end/benders/conftest.py
  tests/end_to_end/examples/conftest.py
  tests/end_to_end/restart/conftest.py
Labels: size/M

#920 avoiding code duplication
  tests/end_to_end/benders/test_bendersEndToEnd.py
  tests/end_to_end/restart/test_restartBendersEndToEnd.py
  tests/end_to_end/utils_functions.py
Labels: size/L

#896 Remove sirius port
  CMakeLists.txt
  conception/Architecture_decision_records/[010] Create_custom_vcpkg_ports_for_deps.md
  conception/Architecture_decision_records/[011]Dont_build_or_port_second degree_dependency.md
  ports/sirius-solver/portfile.cmake
  ports/sirius-solver/vcpkg.json
  vcpkg.json
Labels: size/M

#912 Use release triplet for vcpkg
  .github/workflows/build_centos7.yml
  .github/workflows/build_oracle8.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-system-deps-build.yml
Labels: size/S

#923 fix e2e tests
  tests/end_to_end/examples/example_test.py
Labels: size/XS

#914 Use exact versions from antares deps
  ports/coin-or-cbc/portfile.cmake
  ports/coin-or-cgl/portfile.cmake
  ports/coin-or-clp/portfile.cmake
  ports/coin-or-osi/portfile.cmake
  ports/coinutils/portfile.cmake
Labels: size/M

#910 test with cucumber
  .github/workflows/build_centos7.yml
  .github/workflows/build_oracle8.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  .github/workflows/cucumber-tests/action.yml
  CMakeLists.txt
  data_test/external_loop_test/lp/options.json
  requirements-tests.txt
  src/python/config.yaml.in
  tests/CMakeLists.txt
  tests/cpp/outer_loop/outer_loop_test.cpp
  tests/end_to_end/cucumber/features/outer_loop_tests.feature
  tests/end_to_end/cucumber/steps/__init__.py
  tests/end_to_end/cucumber/steps/steps.py
Labels: size/L

#924 xpress from pip
  .github/workflows/build_centos7.yml
  .github/workflows/build_oracle8.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  data_test/external_loop_test/lp/options.json
  docker/centos7-system-deps
  tests/end_to_end/cucumber/steps/steps.py
Labels: size/L

#927 fix warnings on ActiveLink
  src/cpp/lpnamer/problem_modifier/ProblemVariablesFileAdapter.h
  src/cpp/lpnamer/problem_modifier/ProblemVariablesFromProblemAdapter.h
Labels: size/XS

#930 fix some sonar issues
  src/cpp/benders/factories/BendersFactory.cpp
  src/cpp/multisolver_interface/SolverXpress.cpp
Labels: size/S

#928 fix warnings on solvers interfaces
  src/cpp/helpers/solver_utils.cc
  src/cpp/multisolver_interface/SolverCbc.cpp
  src/cpp/multisolver_interface/SolverXpress.cpp
  src/cpp/multisolver_interface/SolverXpress.h
Labels: size/M
