Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2024-05, with the labels that each got.

#792 [API] Throw exception instead of cerr log
  src/cpp/benders/benders_core/SimulationOptions.cpp
  src/cpp/benders/benders_core/include/SimulationOptions.h
Labels: size/S

#793 Update ubuntu badge
  README.md
  docs/index.md
Labels: size/S

#803 Update badges
  README.md
  docs/index.md
Labels: size/S

#804 Fix userguide generation
  docs/index.md
Labels: size/XS

#806 Fix pdf math rendering
  docs/pdf-doc-generation-with-sphinx/source/conf.py
Labels: size/XS

#807 Update gitignore
  .gitignore
Labels: size/XS

#814 Fix performance issue
  src/cpp/benders/benders_by_batch/BendersByBatch.cpp
Labels: size/XS

#817 Fix criterion computation
  src/cpp/benders/benders_core/BendersBase.cpp
Labels: size/XS

#821 Add lambdas to math logs
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/BendersMathLogger.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/BendersStructsDatas.h
  src/cpp/benders/outer_loop/OuterLoop.cpp
Labels: size/M

#819 Fix sonar issues
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/OuterLoopInputDataReader.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/OuterLoopInputDataReader.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_mpi/include/BendersMPI.h
  src/cpp/benders/benders_sequential/BendersSequential.cpp
  tests/cpp/benders/benders_sequential_test.cpp
Labels: size/M

#797 [API] Better handling of execution modes
  data_test/tests_lpnamer/SmallTestFiveCandidates/output/simulation/interco-1-1.txt
  data_test/tests_lpnamer/tests_integer/test_lpnamer_01/output/economy/area-01.txt
  data_test/tests_lpnamer/tests_integer/test_lpnamer_01/output/economy/interco-01.txt
  data_test/tests_lpnamer/tests_integer/test_one_link_one_candidate_1week/output/economy/area-01.txt
  data_test/tests_lpnamer/tests_integer/test_one_link_one_candidate_1week/output/economy/interco-01.txt
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_1week/output/economy/area-01.txt
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_1week/output/economy/interco-01.txt
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_simple_prob/output/economy/area-01.txt
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_simple_prob/output/economy/interco-01.txt
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_simple_prob_hurdle_cost/output/economy/area-01.txt
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_simple_prob_hurdle_cost/output/economy/interco-01.txt
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_simple_prob_null_profile/output/economy/area-01.txt
  data_test/tests_lpnamer/tests_integer/test_one_link_two_candidates_simple_prob_null_profile/output/economy/interco-01.txt
  data_test/tests_lpnamer/tests_relaxed/SmallTestSixCandidatesWithAlreadyInstalledCapacity-relaxed/output/economy/area-01.txt
  data_test/tests_lpnamer/tests_relaxed/SmallTestSixCandidatesWithAlreadyInstalledCapacity-relaxed/output/economy/interco-01.txt
  data_test/tests_lpnamer/tests_relaxed/test_one_link_one_candidate-relaxed/output/economy/area-01.txt
  data_test/tests_lpnamer/tests_relaxed/test_one_link_one_candidate-relaxed/output/economy/interco-01.txt
  src/cpp/lpnamer/input_reader/LpFilesExtractor.cpp
  src/cpp/lpnamer/input_reader/LpFilesExtractor.h
  src/cpp/lpnamer/main/ProblemGeneration.cpp
  src/cpp/lpnamer/main/ProblemGenerationExeOptions.cpp
  src/cpp/lpnamer/main/include/ProblemGeneration.h
  src/cpp/lpnamer/main/include/ProblemGenerationExeOptions.h
  src/cpp/lpnamer/main/include/ProblemGenerationOptions.h
  src/cpp/lpnamer/model/CMakeLists.txt
  src/cpp/lpnamer/model/SimulationInputMode.h
  tests/cpp/lp_namer/LpFilesExtractorTest.cpp
  tests/cpp/lp_namer/ProblemGenerationExeOptionsTest.cpp
  tests/cpp/lp_namer/StudyUpdateTest.cc
  tests/cpp/solvers_interface/catch2.hpp
  tests/end_to_end/lpnamer/test_lpnamerEndToEnd.py
Labels: size/XL

#805 Update artifact v4
  .github/workflows/build-userguide.yml
  .github/workflows/centos-release.yml
  .github/workflows/ol8-release.yml
  .github/workflows/ubuntu-release.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/M

#824 Outer loop outputs
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/outer_loop/OuterLoop.cpp
  src/cpp/benders/output/JsonWriter.cpp
  src/cpp/xpansion_interfaces/OutputWriter.h
  tests/cpp/TestDoubles/WriterStub.h
Labels: size/M

#826 Remove glog dependency
  CMakeLists.txt
  cmake/json-cmake-1.1.0/JSONParser.cmake
  src/cpp/benders/benders_by_batch/BendersByBatch.cpp
  src/cpp/benders/benders_by_batch/CMakeLists.txt
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/CMakeLists.txt
  src/cpp/benders/benders_core/Worker.cpp
  src/cpp/benders/benders_core/WorkerMaster.cpp
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_mpi/CMakeLists.txt
  src/cpp/benders/benders_sequential/BendersSequential.cpp
  src/cpp/benders/benders_sequential/CMakeLists.txt
  src/cpp/benders/factories/BendersFactory.cpp
  src/cpp/benders/merge_mps/CMakeLists.txt
  src/cpp/benders/merge_mps/MergeMPS.cpp
  src/cpp/exe/merge/main.cpp
  src/cpp/helpers/CMakeLists.txt
Labels: size/M

#823 mpi deps for outerloop
  src/cpp/benders/outer_loop/CMakeLists.txt
  src/cpp/exe/outer_loop/CMakeLists.txt
Labels: size/S

#827 fix case nb procs > nb sub problems
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_mpi/BendersMPI.cpp
Labels: size/S

#828 fix inherit solver type from main
  src/cpp/benders/factories/BendersFactory.cpp
Labels: size/XS
