Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2024-02, with the labels that each got.

#755 Fix build
  .github/workflows/ubuntu-release.yml
  .github/workflows/ubuntu-system-deps-build.yml
Labels: size/S

#736 C4 architecture diagrams
  conception/C4/ContainerDiagram-Container_Diagram_for_Antares.svg
  conception/C4/ContainerDiagram.puml
  conception/C4/ContainerDiagramSimple-Container_Diagram_for_Antares__simple_.svg
  conception/C4/ContainerDiagramSimple.puml
  conception/C4/SystemContextDiagram.puml
  conception/C4/SystemContextDiagram.svg
  conception/C4/XpansionComponent-Component_diagram_for_Xpansion.svg
  conception/C4/XpansionComponent.puml
Labels: size/XXL

#756 [Pb Gen] deal with last study not being a zip
  src/python/antares_xpansion/config_loader.py
Labels: size/S

#759 Release 1.2.2
  .github/workflows/build_oracle8.yml
  .github/workflows/centos-release.yml
  .github/workflows/compile-gtest/action.yml
  .github/workflows/ol8-release.yml
  .github/workflows/windows-vcpkg.yml
  CMakeLists.txt
  antares-version.json
  cmake/dependencies/CMakeLists.txt
  docs/changelog/CHANGELOG.md
  sonar-project.properties
Labels: size/M

#760 ADR subproblem data storage
  conception/Architecture_decision_records/Subproblem_data_storage_for_outer_loop.md
  conception/Architecture_decision_records/images/design_outer_loop.drawio
  conception/Architecture_decision_records/images/design_outer_loop.svg
  conception/Architecture_decision_records/images/design_outer_loop_efficient.drawio
  conception/Architecture_decision_records/images/design_outer_loop_efficient.svg
Labels: size/L

#758 xpress licence in custom path
  src/cpp/multisolver_interface/environment.cc
Labels: size/M

#763 Enable dependabot
  .github/dependabot.yml
  .github/workflows/build-userguide.yml
  .github/workflows/build_centos7.yml
  .github/workflows/build_oracle8.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  .github/workflows/centos-release.yml
  .github/workflows/centos7-system-deps-build.yml
  .github/workflows/doxygen.yml
  .github/workflows/ol8-release.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-release.yml
  .github/workflows/ubuntu-system-deps-build.yml
  .github/workflows/windows-vcpkg-deps-build.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/S

#762 deliver json cpp
  conception/Architecture_decision_records/Install_jsoncpp.md
  conception/Using_jsoncpp_cmake.md
  src/cpp/helpers/CMakeLists.txt
Labels: size/M
