Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2024-07, with the labels that each got.

#861 Changes from 1.3.0
  antares-version.json
  docs/changelog/CHANGELOG.md
  sonar-project.properties
  vcpkg.json
Labels: size/S

#856 Fix missing binding constraints in test
  data_test/tests_lpnamer/SmallTestFiveCandidates/input/bindingconstraints/storing_balance.txt
Labels: size/XS

#829 move criterion computation
  src/cpp/benders/benders_by_batch/BendersByBatch.cpp
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/SubproblemCut.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
Labels: size/M

#836 clean pr #789
  src/cpp/benders/benders_core/OuterLoopBiLevel.cpp
  src/cpp/benders/benders_core/include/OuterLoopBiLevel.h
Labels: size/S

#866 remove number_of_scenarios
  .gitignore
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/SimulationOptions.cpp
  src/cpp/benders/benders_core/include/SimulationOptions.hxx
  src/cpp/benders/benders_core/include/common.h
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/optimisation_keys.py
Labels: size/S

#867 [ant-1860] remove Criterion Tolerance
  data_test/external_loop_test/lp/options.json
  data_test/external_loop_test/lp/outer_loop_options.yml
  src/cpp/benders/benders_core/OuterLoopBiLevel.cpp
  src/cpp/benders/benders_core/OuterLoopInputDataReader.cpp
  src/cpp/benders/benders_core/include/OuterLoopInputDataReader.h
  tests/cpp/outer_loop/outer_loop_test.cpp
Labels: size/S

#870 fix node
  .github/workflows/build_centos7.yml
Labels: size/XS

#872 use system package manager for mpi
  .github/workflows/build_centos7.yml
  .github/workflows/build_oracle8.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/compile-boost/action.yml
  .github/workflows/download-extract-precompiled-libraries-tgz/action.yml
  .github/workflows/sonarcloud.yml
  vcpkg.json
Labels: size/M

#863 [ant-1860] Save not-supplied energy values
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/BendersMathLogger.cpp
  src/cpp/benders/benders_core/OuterLoopInputDataReader.cpp
  src/cpp/benders/benders_core/include/BendersBase.h
  src/cpp/benders/benders_core/include/BendersMathLogger.h
  src/cpp/benders/benders_core/include/BendersStructsDatas.h
  src/cpp/benders/benders_core/include/OuterLoopInputDataReader.h
  src/cpp/benders/benders_core/include/SubproblemCut.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_mpi/include/BendersMPI.h
Labels: size/L

#871 Doc/adequacy criterion
  docs/index.md
  docs/user-guide/get-started/adequacy-criterion.md
  docs/user-guide/get-started/get-started.rst
  docs/user-guide/get-started/installation.md
  docs/user-guide/get-started/launching-optimization.md
  docs/user-guide/optimization-principles/investment-problem.md
  docs/user-guide/optimization-principles/problem-formalization.md
  mkdocs.yml
Labels: size/L

#874 refactor benders factory
  src/cpp/benders/factories/BendersFactory.cpp
Labels: size/S

#873 partial rename outer_loop
  data_test/external_loop_test/lp/adequacy_criterion.yml
  data_test/external_loop_test/lp/options.json
  src/cpp/benders/benders_core/OuterLoopInputDataReader.cpp
  src/cpp/benders/benders_core/include/SimulationOptions.hxx
  src/cpp/benders/outer_loop/OuterLoop.cpp
  src/cpp/exe/full_run/main.cpp
  src/python/antares_xpansion/benders_driver.py
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/input_parser.py
  src/python/antares_xpansion/xpansionConfig.py
  tests/cpp/outer_loop/outer_loop_test.cpp
  tests/python/test_benders_driver.py
Labels: size/M

#876 adequacy_criterion file
  data_test/external_loop_test/lp/options.json
  src/cpp/benders/benders_core/BendersBase.cpp
  src/python/antares_xpansion/config_loader.py
  tests/cpp/outer_loop/outer_loop_test.cpp
Labels: size/S

#877 update test's mps
  data_test/external_loop_test/lp/subproblem.mps
Labels: size/M

#875 Release/1.3.1
  CMakeLists.txt
  antares-version.json
  docs/changelog/CHANGELOG.md
  readthedocs.yml
  requirements-doc.txt
  sonar-project.properties
  vcpkg.json
Labels: size/M

#879 [ANT-1890] Properly handle playlist_reset in generaldata.ini
  src/cpp/lpnamer/input_reader/GeneralDataReader.cpp
  src/cpp/lpnamer/input_reader/GeneralDataReader.h
  tests/cpp/lp_namer/CMakeLists.txt
  tests/cpp/lp_namer/GeneralDataReadetTests.cpp
Labels: size/L

#825 [API]Use antares lib
  .github/workflows/build_centos7.yml
  .github/workflows/build_oracle8.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  .github/workflows/download-extract-precompiled-libraries-tgz/action.yml
  .github/workflows/download-extract-precompiled-libraries-zip/action.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-system-deps-build.yml
  CMakeLists.txt
  antares-version.json
  cmake/dependencies/CMakeLists.txt.in
  data_test/external_loop_test/lp/master_last_basis.bss
  data_test/tests_lpnamer/SmallTestFiveCandidates/output/simulation/README.md
  data_test/tests_lpnamer/SmallTestFiveCandidates/output/simulation/reference_lp/problem-1-1--optim-nb-1.mps
  ports/coin-or-cbc/portfile.cmake
  ports/coin-or-cgl/portfile.cmake
  ports/coin-or-clp/portfile.cmake
  ports/coin-or-osi/portfile.cmake
  ports/coinutils/portfile.cmake
  src/cpp/benders/benders_core/WorkerMaster.cpp
  src/cpp/benders/benders_core/include/WorkerMaster.h
  src/cpp/helpers/ArchiveReader.cpp
  src/cpp/helpers/ArchiveWriter.cpp
  src/cpp/helpers/ArchiveWriter.h
  src/cpp/lpnamer/main/ProblemGeneration.cpp
  src/cpp/lpnamer/model/ActiveLinks.cpp
  src/cpp/lpnamer/model/ActiveLinks.h
  src/cpp/lpnamer/problem_modifier/AntaresProblemToXpansionProblemTranslator.cpp
  src/cpp/lpnamer/problem_modifier/AntaresProblemToXpansionProblemTranslator.h
  src/cpp/lpnamer/problem_modifier/CMakeLists.txt
  src/cpp/lpnamer/problem_modifier/ProblemVariablesFromProblemAdapter.cpp
  src/cpp/lpnamer/problem_modifier/XpansionProblemsFromAntaresProvider.cpp
  src/cpp/multisolver_interface/environment.cc
  src/cpp/multisolver_interface/include/multisolver_interface/dynamic_library.h
  src/cpp/multisolver_interface/include/multisolver_interface/environment.h
  tests/cpp/lp_namer/AntaresProblemToXpansionProblemTranslatorTest.cpp
  tests/cpp/lp_namer/CMakeLists.txt
Labels: size/L

#884 Fix assets due to unproper behaviour of pyinstaller
  .github/workflows/build_centos7.yml
  .github/workflows/build_oracle8.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  .github/workflows/compile-boost/action.yml
  .github/workflows/download-extract-precompiled-libraries-tgz/action.yml
  .github/workflows/sonarcloud.yml
  requirements.txt
  vcpkg.json
Labels: size/M
