Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2025-06, with the labels that each got.

#1056 [ANT-3371] Trajectory investment part 2
  docs/assets/media/trajectory/trajectory.png
  docs/user-guide/trajectory-investment/merge-master.md
  docs/user-guide/trajectory-investment/trajectory-problem.md
  mkdocs.yml
  src/cpp/CMakeLists.txt
  src/cpp/benders/merge_master_mps/MergeMasterMPS.cpp
  src/cpp/benders/merge_master_mps/NodeLpDataLocation.cpp
  src/cpp/benders/merge_mps/include/antares-xpansion/benders/merge_mps/MergeMPS.h
  src/cpp/exe/CMakeLists.txt
  src/cpp/exe/merge-weights-trajectory/CMakeLists.txt
  src/cpp/exe/merge-weights-trajectory/main.cpp
  src/cpp/exe/multiple_problem_generation/CMakeLists.txt
  src/cpp/exe/multiple_problem_generation/main.cpp
  src/cpp/lpnamer/main/CMakeLists.txt
  src/cpp/lpnamer/main/MultipleProblemGeneration.cpp
  src/cpp/lpnamer/main/ProblemGeneration.cpp
  src/cpp/lpnamer/main/ProblemGenerationExeOptions.cpp
  src/cpp/lpnamer/main/include/antares-xpansion/lpnamer/main/MultipleProblemGeneration.h
  src/cpp/lpnamer/main/include/antares-xpansion/lpnamer/main/ProblemGenerationExeOptions.h
  src/cpp/merge_weights_trajectory/CMakeLists.txt
  src/cpp/merge_weights_trajectory/MergeWeightsTrajectory.cpp
  src/cpp/merge_weights_trajectory/include/antares-xpansion/merge_weights_trajectory/MergeWeightsTrajectory.h
  src/python/trajectory_investment/trajectory_driver.py
  src/python/trajectory_investment/trajectory_keys.py
  src/python/trajectory_investment/trajectory_module.py
Labels: size/XXL

#1062 Add del_cols to solver interface and implementations
  src/cpp/lpnamer/model/include/antares-xpansion/lpnamer/model/Problem.h
  src/cpp/multisolver_interface/SolverCbc.cpp
  src/cpp/multisolver_interface/SolverClp.cpp
  src/cpp/multisolver_interface/SolverXpress.cpp
  src/cpp/multisolver_interface/environment.cc
  src/cpp/multisolver_interface/include/antares-xpansion/multisolver_interface/SolverAbstract.h
  src/cpp/multisolver_interface/include/antares-xpansion/multisolver_interface/environment.h
  src/cpp/multisolver_interface/private/SolverCbc.h
  src/cpp/multisolver_interface/private/SolverClp.h
  src/cpp/multisolver_interface/private/SolverXpress.h
  tests/cpp/lp_namer/NOOPSolver.h
  tests/cpp/solvers_interface/define_datas.cpp
  tests/cpp/solvers_interface/define_datas.hpp
  tests/cpp/solvers_interface/test_modifying_problem.cpp
Labels: size/L

#1065 install tbb library
  CMakeLists.txt
Labels: size/XS

#1066 Update badges
  README.md
Labels: size/M
