Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2025-03, with the labels that each got.

#1015 Docs/improve perf graphs
  docs/user-guide/performance-history/perf-graphs.ipynb
  docs/user-guide/performance-history/perf_data.json
  docs/user-guide/performance-history/performance.py
Labels: size/L

#1014 Fix issue and improve coverage
  src/cpp/lpnamer/problem_modifier/include/antares-xpansion/lpnamer/problem_modifier/MPSFileProblemProviderAdapter.h
  tests/CMakeLists.txt
  tests/cpp/lp_namer/CMakeLists.txt
  tests/cpp/lp_namer/MPSFileProblemProviderAdapterTest.cpp
  tests/cpp/merge_mps/merge_mps_test.cpp
  tests/python/test_study_output_cleaner.py
Labels: size/L

#1020 Fix missing coverage data
  cmake/CodeCoverage.cmake
  sonar-project.properties
  tests/CMakeLists.txt
  tests/python/conftest.py
Labels: size/M

#1023 Update antares Simulator to 9.2.0
  .github/workflows/build_ubuntu.yml
  .github/workflows/sonarcloud.yml
  antares-version.json
  vcpkg-configuration.json
Labels: size/XS

#1024 Remove unofficial action lukka/get-cmake [ANT-2997][ANT-3004]
  .github/workflows/build_oracle8.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/ubuntu-system-deps-build.yml
Labels: size/S

#1025 Remove use of bruceadams/get-release & actions/upload-release-asset [ANT-2997][ANT-3005]
  .github/workflows/build-userguide.yml
  .github/workflows/build_centos7.yml
  .github/workflows/build_oracle8.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
Labels: size/M

#1028 Add unit tests on SolverLoader, SolverFactory [ANT-1903]
  tests/cpp/CMakeLists.txt
  tests/cpp/multisolver_interface/CMakeLists.txt
  tests/cpp/multisolver_interface/test_multisolver.cpp
Labels: size/M
