Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2025-07, with the labels that each got.

#1069 Update perf graph for version 1.4.0
  docs/user-guide/performance-history/perf-graphs.ipynb
  docs/user-guide/performance-history/perf_data.json
Labels: size/S

#1070 [ANT-3594] Properly configure Simulator solver options
  src/cpp/lpnamer/main/ProblemGeneration.cpp
  src/python/antares_xpansion/split_link_profile.py
Labels: size/S

#1067 Add coverage for Merge MPS
  tests/cpp/benders/CMakeLists.txt
  tests/cpp/benders/MergeMasterTest.cpp
Labels: size/M

#1072 Add name to feature and scenario
  tests/end_to_end/cucumber/features/SolverE2E.feature
Labels: size/XS
