Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2025-01, with the labels that each got.

#977 Use updated antares-solver API (output path changes) [ANT-2561]
  antares-version.json
  src/cpp/lpnamer/main/ProblemGeneration.cpp
  src/cpp/lpnamer/main/include/antares-xpansion/lpnamer/main/ProblemGeneration.h
  tests/cpp/lp_namer/ProblemGenerationExeOptionsTest.cpp
Labels: size/M

#981 Feature/ant 2561 api e2e solver consistency
  CMakeLists.txt
  antares-version.json
  data_test/examples/dummy-3areas-3candidates-3links/settings/generaldata.ini
  docs/changelog/CHANGELOG.md
  sonar-project.properties
  src/cpp/lpnamer/main/ProblemGeneration.cpp
  src/cpp/lpnamer/main/include/antares-xpansion/lpnamer/main/ProblemGeneration.h
  src/python/antares_xpansion/antares_driver.py
  tests/cpp/lp_namer/ProblemGenerationExeOptionsTest.cpp
  tests/end_to_end/cucumber/features/steps/steps.py
  tests/python/test_antares_driver.py
  vcpkg.json
Labels: size/L

#982 Feature/not removing subpb mps files with merge
  src/cpp/benders/merge_mps/MergeMPS.cpp
Labels: size/XS

#979 Dockerfile to work on centos7 locally
  docker/centos-local-build/README.MD
  docker/centos-local-build/build.sh
  docker/centos-local-build/dockerfile
  docker/centos-local-build/run.sh
Labels: size/L

#985 Properly lock concurrent data access
  src/cpp/benders/benders_core/BendersBase.cpp
Labels: size/XS

#983 Better handling on solver names
  src/cpp/lpnamer/main/ProblemGeneration.cpp
  src/cpp/lpnamer/main/include/antares-xpansion/lpnamer/main/ProblemGeneration.h
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.cpp
  src/cpp/lpnamer/problem_modifier/MPSFileProblemProviderAdapter.cpp
  src/cpp/lpnamer/problem_modifier/include/antares-xpansion/lpnamer/problem_modifier/LinkProblemsGenerator.h
  src/cpp/multisolver_interface/CMakeLists.txt
  src/cpp/multisolver_interface/SolverConfig.cpp
  src/cpp/multisolver_interface/SolverFactory.cpp
  src/cpp/multisolver_interface/include/antares-xpansion/multisolver_interface/SolverConfig.h
  src/cpp/multisolver_interface/include/antares-xpansion/multisolver_interface/SolverFactory.h
Labels: size/L

#987 [ANT-2299] Enable save/restore with xpress and enable by default (Benders)
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/CMakeLists.txt
  src/cpp/benders/benders_core/ProblemFormatStream.cpp
  src/cpp/benders/benders_core/SimulationOptions.cpp
  src/cpp/benders/benders_core/SolverIO.cpp
  src/cpp/benders/benders_core/SubproblemWorker.cpp
  src/cpp/benders/benders_core/Worker.cpp
  src/cpp/benders/benders_core/WorkerMaster.cpp
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/ProblemFormat.h
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/ProblemFormatStream.h
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/SolverIO.h
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/SubproblemWorker.h
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/Worker.h
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/WorkerMaster.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_sequential/BendersSequential.cpp
  src/cpp/lpnamer/problem_modifier/include/antares-xpansion/lpnamer/problem_modifier/MPSFileProblemProviderAdapter.h
  src/python/antares_xpansion/study_output_cleaner.py
  vcpkg.json
Labels: size/L

#988 Handle save/restore in sensitivity
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/ProblemFormatStream.cpp
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/BendersBase.h
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/ProblemFormatStream.h
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/StartUp.h
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/Worker.h
  src/cpp/benders/factories/BendersFactory.cpp
  src/cpp/benders/factories/WriterFactories.cpp
  src/cpp/benders/factories/include/antares-xpansion/benders/factories/WriterFactories.h
  src/cpp/benders/output/CMakeLists.txt
  src/cpp/benders/output/JsonWriter.cpp
  src/cpp/benders/output/VoidWriter.cpp
  src/cpp/benders/output/include/antares-xpansion/benders/output/JsonWriter.h
  src/cpp/benders/output/include/antares-xpansion/benders/output/OutputWriter.h
  src/cpp/benders/output/include/antares-xpansion/benders/output/VoidWriter.h
  src/cpp/sensitivity/CMakeLists.txt
  src/cpp/sensitivity/SensitivityInputReader.cpp
  src/cpp/sensitivity/include/antares-xpansion/sensitivity/SensitivityInputReader.h
  src/cpp/xpansion_interfaces/CMakeLists.txt
  src/python/antares_xpansion/config_loader.py
  src/python/antares_xpansion/sensitivity_driver.py
  tests/cpp/TestDoubles/WriterStub.h
Labels: size/L
