Repository AntaresSimulatorTeam/antares-xpansion, pull requests merged in 2025-02, with the labels that each got.

#990 Weights not correctly read for subproblems
  src/cpp/benders/benders_core/Worker.cpp
  src/cpp/lpnamer/input_reader/MpsTxtWriter.cpp
  src/cpp/lpnamer/input_reader/WeightsFileWriter.cpp
  src/cpp/lpnamer/input_reader/include/antares-xpansion/lpnamer/input_reader/MpsTxtWriter.h
  src/cpp/lpnamer/input_reader/include/antares-xpansion/lpnamer/input_reader/WeightsFileWriter.h
  src/cpp/lpnamer/main/ProblemGeneration.cpp
  src/cpp/lpnamer/main/include/antares-xpansion/lpnamer/main/ProblemGeneration.h
  src/cpp/lpnamer/problem_modifier/LinkProblemsGenerator.cpp
  src/cpp/lpnamer/problem_modifier/MasterGeneration.cpp
  src/cpp/multisolver_interface/SolverConfig.cpp
  src/cpp/multisolver_interface/include/antares-xpansion/multisolver_interface/SolverConfig.h
  src/cpp/sensitivity/SensitivityInputReader.cpp
  src/python/antares_xpansion/problem_generator_driver.py
  tests/cpp/lp_namer/WeightsFileWriterTest.cpp
Labels: size/L

#992 Bump Antares version to 9.2.0-rc10
  antares-version.json
Labels: size/XS

#993 Fix incorrect method call for mps_name in WeightsFileWriter
  antares-version.json
  src/cpp/lpnamer/input_reader/WeightsFileWriter.cpp
  tests/cpp/benders/benders_sequential_test.cpp
  tests/cpp/lp_namer/WeightsFileWriterTest.cpp
Labels: size/M

#995 Replace MockSolverAbstract with NOOPSolver in WeightsFileWriterTest
  tests/cpp/lp_namer/WeightsFileWriterTest.cpp
Labels: size/M

#994 [ANT-2202] Vectorize row and col names change (only available with Xpress) in solver to accelerate problem generation
  src/cpp/helpers/solver_utils.cc
  src/cpp/lpnamer/model/include/antares-xpansion/lpnamer/model/Problem.h
  src/cpp/lpnamer/problem_modifier/AntaresProblemToXpansionProblemTranslator.cpp
  src/cpp/lpnamer/problem_modifier/LauncherHelpers.cpp
  src/cpp/multisolver_interface/SolverCbc.cpp
  src/cpp/multisolver_interface/SolverClp.cpp
  src/cpp/multisolver_interface/SolverXpress.cpp
  src/cpp/multisolver_interface/include/antares-xpansion/multisolver_interface/SolverAbstract.h
  src/cpp/multisolver_interface/private/SolverCbc.h
  src/cpp/multisolver_interface/private/SolverClp.h
  src/cpp/multisolver_interface/private/SolverXpress.h
  tests/cpp/lp_namer/NOOPSolver.h
  tests/cpp/solvers_interface/test_exceptions.cpp
  tests/cpp/solvers_interface/test_modifying_problem.cpp
Labels: size/L

#996 Minor fixes
  src/cpp/benders/benders_by_batch/BendersByBatch.cpp
  src/cpp/benders/benders_by_batch/include/antares-xpansion/benders/benders_by_batch/BendersByBatch.h
  src/cpp/benders/benders_core/BendersBase.cpp
  src/cpp/benders/benders_core/CriterionComputation.cpp
  src/cpp/benders/benders_core/StartUp.cpp
  src/cpp/benders/benders_core/SubproblemWorker.cpp
  src/cpp/benders/benders_core/Worker.cpp
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/BendersBase.h
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/StartUp.h
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/SubproblemWorker.h
  src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/Worker.h
  src/cpp/benders/benders_mpi/BendersMPI.cpp
  src/cpp/benders/benders_mpi/BendersMpiOuterLoop.cpp
  src/cpp/benders/benders_mpi/include/antares-xpansion/benders/benders_mpi/BendersMPI.h
  src/cpp/benders/benders_mpi/include/antares-xpansion/benders/benders_mpi/BendersMpiOuterLoop.h
  src/cpp/benders/benders_sequential/BendersSequential.cpp
  src/cpp/benders/benders_sequential/include/antares-xpansion/benders/benders_sequential/BendersSequential.h
  src/cpp/benders/factories/BendersFactory.cpp
  src/cpp/benders/factories/WriterFactories.cpp
  src/cpp/benders/factories/include/antares-xpansion/benders/factories/BendersFactory.h
  src/cpp/benders/factories/include/antares-xpansion/benders/factories/WriterFactories.h
  src/cpp/benders/merge_mps/MergeMPS.cpp
  src/cpp/benders/merge_mps/include/antares-xpansion/benders/merge_mps/MergeMPS.h
  src/cpp/benders/output/include/antares-xpansion/benders/output/OutputWriter.h
  src/cpp/exe/merge/main.cpp
  tests/cpp/benders/benders_sequential_test.cpp
  tests/cpp/outer_loop/outer_loop_test.cpp
  tests/cpp/restart_benders/restart_lib_tests.cpp
Labels: size/L

#998 Improve problem generation performance
  src/cpp/lpnamer/main/ProblemGeneration.cpp
  src/cpp/lpnamer/main/include/antares-xpansion/lpnamer/main/ProblemGeneration.h
  src/cpp/lpnamer/problem_modifier/AntaresProblemToXpansionProblemTranslator.cpp
  src/cpp/lpnamer/problem_modifier/XpansionProblemsFromAntaresProvider.cpp
  src/cpp/lpnamer/problem_modifier/include/antares-xpansion/lpnamer/problem_modifier/XpansionProblemsFromAntaresProvider.h
Labels: size/M

#1002 Remove inexact note in docs
  docs/user-guide/get-started/candidate-definition.md
Labels: size/XS

#1001 Add performance data for version 1.4
  docs/user-guide/performance-history/perf-graphs.ipynb
  docs/user-guide/performance-history/perf_data.json
Labels: size/M

#1003 Improve tests, sonar and coverage
  .github/workflows/sonarcloud.yml
  tests/CMakeLists.txt
Labels: size/M

#1005 Enable all test in sonar CI
  .github/workflows/sonarcloud.yml
Labels: size/XS

#1008 Fix version of pip xpress to 9.2.7
  .github/workflows/build_oracle8.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-system-deps-build.yml
  .github/workflows/windows-vcpkg-deps-build.yml
  docker/centos7-system-deps
Labels: size/S

#1010 Coverage exclusion
  sonar-project.properties
Labels: size/XS

#1013 Code coverage for e2e tests
  tests/CMakeLists.txt
Labels: size/M
